import { alpha } from "@mui/material";

export const getRocketMotorCasingTheme = (baseTheme: any) => {
	const palette = baseTheme?.palette ?? {};

	return {
		header: {
			warningChip: {
				background: alpha(palette.warn ?? "#D4AC0D", 0.14),
				color: palette.warn ?? "#D4AC0D",
			},
		},
		form: {
			readinessHintColor: palette.success ?? "#148F77",
		},
		createForm: {
			pageRoot: { display: "flex", flexDirection: "column", gap: 2.5 },
			headerRow: {
				display: "flex",
				alignItems: "flex-start",
				justifyContent: "space-between",
				flexWrap: "wrap",
				gap: 1.5,
				mb: 0.5,
			},
			sectionCard: (index = 0) => ({
				borderRadius: 3.5,
				border: `1px solid ${palette.border}`,
				background: palette.surface ?? "#fff",
				overflow: "hidden",
				boxShadow: `0 2px 14px ${alpha(palette.primary ?? "#1B4F72", 0.06)}`,
				animation: "fadeIn 0.35s ease both",
				animationDelay: `${index * 0.05}s`,
			}),
			sectionCardHeader: (accentColor: string) => ({
				px: 2,
				py: 1.5,
				display: "flex",
				alignItems: "center",
				justifyContent: "space-between",
				gap: 1.5,
				background: `linear-gradient(135deg, ${alpha(palette.primary ?? "#1B4F72", 0.07)}, ${alpha(palette.primaryLight ?? "#2E86C1", 0.04)})`,
				borderBottom: `1px solid ${palette.border}`,
				borderLeft: `4px solid ${accentColor}`,
			}),
			sectionCardBody: { px: 2, py: 2 },
			sectionCardBodyDisabled: {
				opacity: 0.48,
				pointerEvents: "none",
				userSelect: "none",
				filter: "grayscale(0.12)",
			},
			identificationGateHint: {
				fontSize: "0.8rem",
				fontWeight: 600,
				color: palette.textSub,
				lineHeight: 1.45,
				px: 1.5,
				py: 1.25,
				mb: 0.5,
				borderRadius: 2,
				border: `1px dashed ${alpha(palette.primaryLight ?? "#2E86C1", 0.45)}`,
				background: alpha(palette.primaryLight ?? "#2E86C1", 0.05),
			},
			sectionNumber: {
				width: 26,
				height: 26,
				borderRadius: "8px",
				flexShrink: 0,
				display: "flex",
				alignItems: "center",
				justifyContent: "center",
				background: `linear-gradient(135deg, ${palette.primary}, ${palette.primaryLight})`,
				color: "#fff",
				fontSize: "0.72rem",
				fontWeight: 800,
			},
			sectionTitle: { fontWeight: 800, fontSize: "0.88rem", color: palette.text, lineHeight: 1.3 },
			sectionSubtitle: { fontSize: "0.72rem", color: palette.textSub, mt: 0.25 },
			subsectionTitle: {
				fontSize: "0.7rem",
				fontWeight: 800,
				letterSpacing: "0.08em",
				textTransform: "uppercase",
				color: palette.primaryLight,
				mb: 1.25,
				mt: 0.5,
			},
			fieldGrid: {
				display: "grid",
				gridTemplateColumns: { xs: "1fr", sm: "repeat(2, 1fr)", lg: "repeat(3, 1fr)" },
				gap: 2,
				alignItems: "start",
			},
			fieldGridWide: {
				display: "grid",
				gridTemplateColumns: { xs: "1fr", md: "repeat(2, 1fr)" },
				gap: 2,
				alignItems: "start",
			},
			projectOption: {
				display: "flex",
				flexDirection: "column",
				gap: 0.25,
				py: 0.25,
				width: "100%",
			},
			projectOptionName: {
				fontSize: "0.84rem",
				fontWeight: 700,
				color: palette.text,
				lineHeight: 1.3,
			},
			projectOptionId: {
				fontSize: "0.72rem",
				fontWeight: 700,
				color: palette.primaryLight ?? palette.primary,
				fontFamily: "monospace",
				letterSpacing: "0.04em",
				lineHeight: 1.2,
			},
			projectOptionSelected: {
				display: "flex",
				alignItems: "baseline",
				gap: 1,
				minWidth: 0,
				overflow: "hidden",
			},
			fieldFullWidth: { gridColumn: { xs: "1", md: "1 / -1" } },
			divider: {
				my: 2,
				borderTop: `1px dashed ${alpha(palette.border, 0.9)}`,
			},
			ndtSection: {
				display: "flex",
				flexDirection: "column",
				gap: 2,
			},
			ndtDatesRow: {
				display: "grid",
				gridTemplateColumns: { xs: "1fr", sm: "repeat(2, minmax(220px, 1fr))" },
				gap: 2,
				maxWidth: 560,
			},
			ndtObservationsGrid: {
				display: "grid",
				gridTemplateColumns: {
					xs: "1fr",
					sm: "repeat(2, minmax(0, 1fr))",
					lg: "repeat(4, minmax(0, 1fr))",
				},
				gap: 2,
				alignItems: "start",
				pt: 0.25,
			},
			visualRow: (index: number) => ({
				px: 1.25,
				py: 1,
				borderRadius: 2,
				mb: 0.75,
				border: `1px solid ${alpha(palette.border, 0.65)}`,
				background: index % 2 === 0 ? alpha(palette.surface, 0.5) : "#fff",
			}),
			visualRowTitle: {
				fontWeight: 700,
				fontSize: "0.8rem",
				flex: 1,
				minWidth: 0,
				lineHeight: 1.35,
			},
			visualInspectionGrid: {
				display: "grid",
				gridTemplateColumns: {
					xs: "1fr",
					sm: "repeat(2, minmax(0, 1fr))",
				},
				gap: 1.25,
				alignItems: "start",
				mt: 0.75,
			},
			visualSubGrid: {
				display: "grid",
				gridTemplateColumns: { xs: "1fr", sm: "repeat(2, minmax(0, 1fr))" },
				gap: 1,
				ml: { xs: 0, sm: 1.5 },
				pl: { xs: 0, sm: 1.25 },
				mt: 0.75,
				pt: 0.75,
				borderLeft: { xs: "none", sm: `2px solid ${alpha(palette.primaryLight, 0.35)}` },
				borderTop: { xs: `1px dashed ${alpha(palette.border, 0.7)}`, sm: "none" },
			},
			visualSubLabel: {
				fontSize: "0.74rem",
				fontWeight: 600,
				color: palette.textSub,
				gridColumn: { xs: "1 / -1", sm: "1 / -1" },
				mb: -0.25,
			},
			compactMediaWrap: {
				mt: 1,
			},
			propertiesPanel: {
				borderRadius: 2,
				border: `1px solid ${palette.border}`,
				overflow: "hidden",
				mt: 1,
			},
			specChip: {
				height: 20,
				fontSize: "0.62rem",
				fontWeight: 700,
				background: alpha(palette.warn ?? "#D4AC0D", 0.1),
				color: palette.warn ?? "#D4AC0D",
				border: `1px solid ${alpha(palette.warn ?? "#D4AC0D", 0.25)}`,
			},
			looseFlapBanner: {
				fontSize: "0.68rem",
				fontWeight: 600,
				color: palette.textSub,
				mb: 0.75,
				fontStyle: "italic",
			},
			stepNav: {
				root: {
					mt: 2,
					p: "14px 16px",
					borderRadius: 2.5,
					border: `1px solid ${palette.border}`,
					background: "#fff",
				},
				stepCounter: {
					fontSize: "0.72rem",
					fontWeight: 700,
					letterSpacing: "0.06em",
					textTransform: "uppercase",
					color: palette.textSub,
				},
				stepChip: (active: boolean, done: boolean, theme: any, navigable = false) => ({
					height: 24,
					fontSize: "0.65rem",
					fontWeight: 700,
					...(active
						? {
								background: `linear-gradient(135deg, ${palette.primary}, ${palette.primaryLight})`,
								color: "#fff",
							}
						: done
							? {
									background: alpha(palette.accent ?? "#148F77", 0.12),
									color: palette.accent ?? "#148F77",
									border: `1px solid ${alpha(palette.accent ?? "#148F77", 0.25)}`,
								}
							: {
									background: alpha(theme.palette.textSub, 0.06),
									color: palette.textSub,
								}),
					...(navigable && !active
						? {
								cursor: "pointer",
								"&:hover": {
									background: alpha(palette.primaryLight ?? "#2E86C1", 0.14),
									color: palette.primary ?? "#1B4F72",
								},
							}
						: navigable
							? { cursor: "pointer" }
							: { cursor: "default", opacity: 0.55 }),
				}),
				backButton: (theme: any) => ({
					borderRadius: 2,
					fontWeight: 700,
					textTransform: "none",
					borderColor: palette.primaryLight,
					color: palette.primaryLight,
					"&:hover": { background: alpha(palette.primaryLight, 0.06) },
					"&:disabled": { borderColor: palette.border, color: theme.palette.textSub },
				}),
				nextButton: (theme: any, hasError = false) => ({
					borderRadius: 2,
					fontWeight: 800,
					textTransform: "none",
					background: `linear-gradient(135deg, ${palette.primary}, ${palette.primaryLight})`,
					boxShadow: `0 4px 12px ${alpha(palette.primary, 0.28)}`,
					"&:hover": { boxShadow: `0 6px 16px ${alpha(palette.primary, 0.38)}` },
					"&:disabled": { background: palette.border, boxShadow: "none", color: "#fff" },
					...(hasError
						? {
								boxShadow: `0 0 0 2px ${alpha(theme.palette.danger, 0.35)}`,
							}
						: {}),
				}),
				errorBanner: (theme: any) => ({
					display: "flex",
					alignItems: "flex-start",
					gap: 0.75,
					maxWidth: 320,
					px: 1.25,
					py: 1,
					borderRadius: 1.5,
					background: alpha(theme.palette.danger, 0.08),
					border: `1px solid ${alpha(theme.palette.danger, 0.28)}`,
				}),
				errorIcon: (theme: any) => ({
					fontSize: 18,
					color: theme.palette.danger,
					flexShrink: 0,
					mt: 0.1,
				}),
				stepError: (theme: any) => ({
					fontSize: "0.78rem",
					fontWeight: 600,
					color: theme.palette.danger,
					lineHeight: 1.45,
					textAlign: "left",
				}),
				hint: (theme: any) => ({
					mt: 1.25,
					fontSize: "0.72rem",
					color: theme.palette.textSub,
				}),
			},
		},
		casingForm: {
			root: { fontFamily: "'DM Sans', sans-serif" },
			editModeIcon: { fontSize: 18, flexShrink: 0 },
			editModeBanner: {
				mb: 2.5,
				px: 2,
				py: 1.5,
				borderRadius: 2,
				background: alpha(palette.danger ?? "#C0392B", 0.05),
				border: `1.5px solid ${alpha(palette.danger ?? "#C0392B", 0.2)}`,
				display: "flex",
				alignItems: "center",
				gap: 1.2,
			},
			editModeBannerText: {
				fontSize: "0.75rem",
				color: palette.danger ?? "#C0392B",
				fontWeight: 600,
				lineHeight: 1.5,
			},
			headerIconBox: {
				width: 32,
				height: 32,
				borderRadius: "10px",
				background: `linear-gradient(135deg, ${palette.primary ?? "#1B4F72"}, ${palette.primaryLight ?? "#2E86C1"})`,
				display: "flex",
				alignItems: "center",
				justifyContent: "center",
				boxShadow: `0 4px 10px ${alpha(palette.primary ?? "#1B4F72", 0.28)}`,
			},
			headerLaunchIcon: { color: "#fff", fontSize: 17 },
			headerTitle: {
				fontWeight: 800,
				fontSize: "0.92rem",
				color: palette.text,
			},
			headerSubtitle: {
				fontSize: "0.75rem",
				color: palette.textSub,
				mt: 0.3,
			},
			mandatoryChip: {
				height: 22,
				fontSize: "0.65rem",
				fontWeight: 700,
				background: alpha(palette.danger ?? "#C0392B", 0.08),
				color: palette.danger ?? "#C0392B",
				border: `1px solid ${alpha(palette.danger ?? "#C0392B", 0.2)}`,
				"& .MuiChip-icon": { ml: "5px" },
			},
			mandatoryChipIcon: { fontSize: "12px !important" },
			sectionChip: (color: string) => ({
				height: 17,
				fontSize: "0.58rem",
				fontWeight: 700,
				background: alpha(color || palette.primaryLight, 0.1),
				color: color || palette.primaryLight,
				border: `1px solid ${alpha(color || palette.primaryLight, 0.2)}`,
			}),
			subFieldContainer: {
				pl: 1.5,
				borderLeft: `2px solid ${alpha(palette.primaryLight ?? "#2E86C1", 0.25)}`,
				mb: 1.5,
			},
			subFieldArrow: { fontSize: 13, color: alpha(palette.primaryLight ?? "#2E86C1", 0.6) },
			subFieldLabel: { fontSize: "0.74rem", fontWeight: 700, color: palette.textSub },
			emptyStateIcon: { fontSize: 28, color: alpha(palette.primaryLight ?? "#2E86C1", 0.3), mb: 0.5 },
			emptyStateTitle: { fontSize: "0.78rem", color: palette.textSub, fontWeight: 600 },
			emptyStateSubtitle: { fontSize: "0.7rem", color: palette.textSub },
			dimTopMetaRow: { mb: 1.5, display: "flex", alignItems: "center", gap: 1.5 },
			tableContainer: {
				borderRadius: "8px",
				border: `1px solid ${palette.border}`,
				boxShadow: `0 1px 6px ${alpha(palette.primary ?? "#1B4F72", 0.05)}`,
			},
			tableHeaderLead: { minWidth: 200, width: "28%" },
			tableHeaderCell: (isRemarks = false) => ({
				minWidth: isRemarks ? 160 : 100,
				width: isRemarks ? "20%" : "13%",
				...(isRemarks
					? { background: `linear-gradient(135deg, ${palette.accent ?? "#148F77"}, ${palette.accentLight ?? "#1ABC9C"})` }
					: {}),
			}),
			dataRow: (isEven: boolean) => ({
				background: isEven ? palette.surface : alpha(palette.surface ?? "#F4F6F8", 0.55),
				"&:hover": { background: alpha(palette.primaryLight ?? "#2E86C1", 0.04) },
				"&:last-child td": { borderBottom: "none" },
			}),
			paramIndexBadge: {
				width: 18,
				height: 18,
				borderRadius: "4px",
				flexShrink: 0,
				background: `linear-gradient(135deg, ${palette.primary}, ${palette.primaryLight})`,
				display: "flex",
				alignItems: "center",
				justifyContent: "center",
			},
			paramIndexText: {
				fontSize: "0.55rem",
				fontWeight: 800,
				color: "#fff",
				lineHeight: 1,
			},
			paramNameText: {
				fontSize: "0.75rem",
				fontWeight: 600,
				color: palette.textSub,
			},
			remarksCellField: {
				"& .MuiOutlinedInput-root": { alignItems: "flex-start" },
				"& .MuiInputBase-input": { padding: "5px 7px", fontSize: "0.75rem" },
			},
			dimInput: { "& .MuiInputBase-input": { textAlign: "center" } },
			dimSubHeader: {
				fontSize: "0.68rem",
				fontWeight: 700,
				py: 0.75,
				whiteSpace: "nowrap",
			},
			sectionColors: {
				motorId: palette.primaryLight ?? "#2E86C1",
				clearance: palette.accent ?? "#148F77",
				insulation: "#7D3C98",
				waivers: palette.warn ?? "#D4AC0D",
				visual: palette.accentLight ?? "#1ABC9C",
				dimensional: "#1A5276",
				mockTrial: "#6C3483",
			},
			footerNoteText: {
				fontSize: "0.7rem",
				color: palette.textSub,
				lineHeight: 1.5,
			},
			footerInfoIcon: { fontSize: 14, color: palette.primaryLight, flexShrink: 0 },
			sectionHeaderLabel: { fontSize: "0.82rem", fontWeight: 700, color: palette.text },
			sectionRow: { mb: 1 },
		},
		casingDetails: {
			/** Opaque chips for the dark gradient banner (batch-list tints are too faint here). */
			bannerStatusConfig: (() => {
				const warnBase = palette.warn ?? "#D4AC0D";
				const primary = palette.primary ?? "#1B4F72";
				const primaryLight = palette.primaryLight ?? "#2E86C1";
				const success = palette.success ?? "#148F77";
				const danger = palette.danger ?? "#C0392B";
				return {
					["Initiated"]: {
						color: "#334155",
						bg: "#F8FAFC",
						border: "#CBD5E1",
					},
					["In Progress"]: {
						color: primary,
						bg: "#E8F4FC",
						border: alpha(primaryLight, 0.5),
					},
					["Waiting for Approval"]: {
						color: "#7D6608",
						bg: "#FFF4D6",
						border: warnBase,
					},
					["Approved"]: {
						color: success,
						bg: "#E8F8F5",
						border: alpha(success, 0.5),
					},
					["Rejected"]: {
						color: danger,
						bg: "#FDEDEC",
						border: alpha(danger, 0.5),
					},
				} as Record<string, { color: string; bg: string; border: string }>;
			})(),
			page: { animation: "fadeIn 0.35s ease both" },
			document: {
				borderRadius: 3,
				border: `1px solid ${palette.border ?? "#D5D8DC"}`,
				boxShadow: `0 4px 24px ${alpha(palette.primary ?? "#1B4F72", 0.08)}`,
				overflow: "hidden",
				background: palette.pageBg ?? "#fff",
			},
			banner: {
				p: "18px 24px",
				background: `linear-gradient(135deg, ${palette.primary}, ${palette.primaryLight})`,
				color: "#fff",
			},
			bannerTitle: { fontWeight: 800, fontSize: "1.05rem", color: "#fff" },
			bannerSubtitle: { fontSize: "0.78rem", color: alpha("#fff", 0.78), mt: 0.35 },
			bannerIcon: { fontSize: 28, color: "#fff", opacity: 0.95 },
			body: { p: { xs: 2, sm: 3 }, background: palette.surface ?? palette.pageBg },
			section: {
				mb: 3,
				p: 2,
				borderRadius: 2,
				border: `1px solid ${alpha(palette.border ?? "#D5D8DC", 0.65)}`,
				background: palette.pageBg ?? "#fff",
			},
			sectionTitle: {
				fontSize: "0.72rem",
				fontWeight: 800,
				letterSpacing: "0.08em",
				textTransform: "uppercase",
				color: palette.primaryLight,
				mb: 1.5,
				display: "flex",
				alignItems: "center",
				gap: 0.75,
			},
			metaGrid: {
				display: "grid",
				gridTemplateColumns: { xs: "1fr", sm: "1fr 1fr", md: "repeat(3, 1fr)" },
				gap: 1.5,
			},
			metaItem: {
				p: 1.25,
				borderRadius: 1.5,
				background: alpha(palette.primaryLight ?? "#2E86C1", 0.04),
				border: `1px solid ${alpha(palette.primaryLight ?? "#2E86C1", 0.12)}`,
			},
			metaLabel: { fontSize: "0.62rem", fontWeight: 700, letterSpacing: "0.06em", textTransform: "uppercase", color: palette.textSub },
			metaValue: { fontSize: "0.88rem", fontWeight: 700, color: palette.text, mt: 0.35 },
			blockWrapper: (isLast: boolean) => ({ mb: isLast ? 0 : 2.5 }),
			blockMeta: { fontSize: "0.72rem", color: palette.textSub },
			blockMetaStrong: { color: palette.text, fontWeight: 700 },
			materialChip: {
				height: 22,
				fontSize: "0.68rem",
				fontWeight: 800,
				background: `linear-gradient(135deg, ${palette.primary}, ${palette.primaryLight})`,
				color: "#fff",
			},
			tableContainer: {
				borderRadius: 1.5,
				border: `1px solid ${palette.border ?? "#D5D8DC"}`,
				overflow: "hidden",
			},
			tableHeaderCell: (isLead: boolean) => ({
				background: isLead
					? `linear-gradient(135deg, ${palette.primary}, ${palette.primaryLight})`
					: alpha(palette.primary ?? "#1B4F72", 0.06),
				color: isLead ? "#fff" : palette.textSub,
				fontWeight: 700,
				fontSize: "0.63rem",
				letterSpacing: "0.05em",
				textTransform: "uppercase",
				py: 1,
				px: 1.5,
				borderBottom: `1px solid ${palette.border}`,
				whiteSpace: "nowrap",
			}),
			tableRow: (idx: number) => ({
				background: idx % 2 === 0 ? palette.pageBg ?? "#fff" : alpha(palette.surface ?? "#F4F6F8", 0.5),
			}),
			tableCell: { fontSize: "0.82rem", py: 1.1, px: 1.5, color: palette.text },
			specText: { fontWeight: 600 },
			resultText: { fontWeight: 600, color: palette.text },
			remarksText: { fontSize: "0.8rem", color: palette.textSub },
			specRangeChip: {
				height: 22,
				fontSize: "0.65rem",
				fontWeight: 600,
				background: alpha(palette.warn ?? "#D4AC0D", 0.1),
				color: palette.warn ?? "#7D6608",
				border: `1px solid ${alpha(palette.warn ?? "#D4AC0D", 0.28)}`,
				whiteSpace: "nowrap",
			},
			dimReadingCell: { fontWeight: 700, color: palette.primary, textAlign: "center" as const },
			dimParamCell: { fontWeight: 600, minWidth: 160 },
			emptyText: { fontSize: "0.85rem", color: palette.textSub, textAlign: "center", py: 4 },
			loadingBox: { minHeight: 320, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 1.5 },
		},
	};
};

export default getRocketMotorCasingTheme;
