/* ===========================
   Global Application Strings
=========================== */

export const STRINGS = {
  /* -------- AUTH -------- */
  AUTH: {
    LOGIN_SUCCESS: (username = "") => {
      const name = username.charAt(0).toUpperCase() + username.slice(1).toLowerCase();

      return `Welcome ${name}, Login Successful`;
    },
    LOGIN_FAILED: "Login failed. Please try again.",
    INVALID_CREDENTIALS: "Invalid credentials or session expired.",
    RESET_SUCCESS: "Password reset successful. Please login with your new password.",
    RESET_FAILED: "Password reset failed. Please try again.",
    
    /* Login */
    LOGIN_TITLE: "Login",
    LOGIN_SUBTITLE: "Enter your access details",
    USERNAME_LABEL: "Username",
    PASSWORD_LABEL: "Password",
    LOGIN_BUTTON: "Login",
    FORGOT_PASSWORD: "Forgot password or first-time reset?",
    /* Features - Left Panel Information */
    FEATURES: [
      {
        title: "Blockchain Security",
        description: "Every transaction is recorded as an immutable block, ensuring complete data integrity and traceability.",
      },
      {
        title: "Real-Time Monitoring",
        description: "Track all processing activities from raw material receipt to final dispatch with live updates.",
      },
      {
        title: "Complete Transparency",
        description: "Access comprehensive audit trails and maintain full visibility across the entire propellant lifecycle.",
      },
    ],

    // FOOTER_NOTE: "Secured with blockchain technology • All rights reserved",
    FOOTER_TEXT: "Designed and Developed by Bharat Electronics Limited © 2026 . All rights reserved.",
    // POLICY: "Privacy Policy",

    /* Reset Password (request from login) */
    RESET_TITLE: "Request password reset",
    RESET_SUBTITLE: "Enter your user ID and reason. Your request will be reviewed by an administrator.",
    USER_ID_LABEL: "User ID",
    REASON_LABEL: "Reason for password reset request",
    REQUEST_RESET_BUTTON: "Request Password Reset",
    DEPARTMENT_LABEL: "Department",
    NEW_PASSWORD_LABEL: "New Password",
    RESET_BUTTON: "Reset Password",
    BACK_TO_LOGIN: "Back to login",
    RESET_REQUEST_SUCCESS: "Your password reset request has been submitted.",

    /* Reset Password API Error Messages */
    RESET_INVALID_INPUT: "Invalid request. Please ensure all fields are properly filled.",
    RESET_USER_NOT_FOUND: "User not found. Please check your user ID and try again.",
    RESET_ALREADY_EXISTS: "A password reset request is already pending for your account. Please wait for the previous request to be processed or contact support.",
    RESET_RATE_LIMITED: "Too many reset requests made. Please try again after some time.",
    
    /* Logout */
    LOGOUT_SUCCESS: "Logged out successfully.",

    // ── Field validation messages ──────────────────────────────────────────
    VALIDATION: {
      ROLE_REQUIRED:       "Please select a role to continue.",
      DEPARTMENT_REQUIRED: "Please select a department for your role.",
      USERNAME_REQUIRED:   "Username is required.",
      PASSWORD_REQUIRED:   "Password is required.",
      PASSWORD_INVALID:
        "Password must start with an uppercase letter, be at least 8 characters, include at least one number, include at least one special character, and contain both uppercase and lowercase letters.",
      USER_ID_REQUIRED:    "User ID is required.",
      REASON_REQUIRED:     "Please describe the reason for your request.",
      CAPTCHA_REQUIRED:    "Please enter the captcha.",
      CAPTCHA_INVALID:     "Captcha does not match. Please try again.",
    },
    LOADING_LOOKUPS: "Loading roles and departments…",
    NO_ROLES_AVAILABLE:
      "No roles are available right now. Refresh the page or try again later.",
    NO_SUBDEPARTMENTS_FOR_LOGIN:
      "No sub-departments could be loaded. You may be unable to complete sign-in for User or Approver roles.",
    ACCESS_DENIED_DEPT: "Access Denied for this department.",
    ERRORS: {
      FETCH_ROLES_FAILED: "[LoginPage] fetchRoles failed:",
      FETCH_DEPTS_FAILED: "[LoginPage] fetchDepartments failed:",
      FETCH_SUB_DEPTS_FAILED: "[LoginPage] fetchSubDepartments() failed:",
      LOOKUP_UNEXPECTED: "[LoginPage] Lookup loading unexpected error:",
    },
    LOGS: {
      LOAD_START: "[LoginPage] Loading roles + sub-departments lookups...",
      API_ROLES: "[LoginPage] -> API: fetchRoles()",
      API_DEPTS: "[LoginPage] -> API: fetchDepartments() (to build sub-department dropdown)",
      ROLES_LOADED: "[LoginPage] roles loaded:",
      DEPTS_LOADED_PREFIX: "[LoginPage] departments loaded: ",
      API_SUB_DEPTS: "[LoginPage] -> API: fetchSubDepartments(departmentId) for each department",
      FETCH_SUB_FOR: "[LoginPage]   fetchSubDepartments for:",
      SUB_DEPTS_IDX: "[LoginPage]   sub-departments for department index ",
      SUB_DEPTS_FAIL_IDX: "[LoginPage]   sub-departments fetch failed for department index ",
      FB_FETCH_ALL: "[LoginPage] No sub-departments via per-department fetch; trying fetchSubDepartments() (no departmentId) ...",
      SUB_ALL_LOADED: "[LoginPage] sub-departments loaded (all):",
    }
  },

  /* -------- SYSTEM / API -------- */
  SYSTEM: {
    UNEXPECTED_ERROR: "Unexpected system error occurred.",
    SERVER_NOT_REACHABLE: "Server not reachable. Please try again later.",
    SESSION_EXPIRED: "Session expired. Please login again.",
    ACCESS_DENIED: "Access denied.",
    RESOURCE_NOT_FOUND: "Requested resource not found.",
    INVALID_REQUEST: "Invalid request.",
    SERVER_ERROR: "Server error. Try again later.",
    UNKNOWN_ERROR: "Unexpected error occurred.",
    CONFLICT: "Request conflicts with existing data. Please check and try again.",
    TOO_MANY_REQUESTS: "Too many requests. Please try again later.",
  },

  /* -------- DASHBOARD HEADER -------- */
  DASHBOARD: {
    TITLE: "Propellant Processing System",
    SUBTITLE: "Integrated Blockchain Traceability and Data Capture",
    SYSTEM_OVERVIEW: {
      HEADING: "System Overview : End-to-End Propellant Lifecycle Management",
      DESCRIPTION:
        "This platform serves as the central hub for all processing activities, ensuring complete transparency and immutability. Every transaction, from raw material receipt to final dispatch, is recorded as an incorruptible block.",
    },
  },
   /* -------- LOGIN DESCRIPTION -------- */
  LOGIN_DETAILS: {
    TITLE: "Blockchain Based Propellant Processing System",
    SUBTITLE: "Integrated Blockchain Traceability and Data Capture",
    CLIENT_DETAILS:{
      DEPARTMENT_NAME: "Advanced Centre for Energetic Materials (ACEM)",
      RESEARCH_DETAILS: "DEFENCE RESEARCH & DEVELOPMENT ORGANISATION (DRDO)",
      ORG_NAME: "GOVT. OF INDIA, MINISTRY OF DEFENCE "
    },
    SYSTEM_OVERVIEW: {
      HEADING: "System Overview : End-to-End Propellant Lifecycle Management",
      DESCRIPTION:
        "This platform serves as the central hub for all processing activities, ensuring complete transparency and immutability. Every transaction, from raw material receipt to final dispatch, is recorded as an incorruptible block.",
    },
  },
  
  /* -------- CAPTCHA -------- */
  CAPTCHA: {
    LABEL:              "Enter Captcha",
    RELOAD_BUTTON:      "Reload",
    LOADING_TEXT:       "Loading…",
    FAILED_TO_LOAD:     "Failed to load",
    HELPER_INCORRECT:   "Incorrect captcha",
    HELPER_ENTERED:    "✓ Captcha entered",
    HELPER_MATCHED:     "✓ Matched",
    HELPER_EMPTY:       "Please enter the captcha",
    HELPER_PLACEHOLDER: "\u00a0",
    ALT_TEXT:           "captcha",
    CONSOLE_ERR:        "[CaptchaField] fetchCaptcha error:",
  },

  /* -------- APP HEADER -------- */
  APP_HEADER: {
    DEFAULT_TITLE:  "Blockchain Based Propellant Processing System",
    ORG_NAME:       "DRDO - ACEM",
    ORG_COUNTRY:    "Govt. of India",
    DRDO_ALT:       "DRDO",
    LOGOUT_LABEL:   "Logout",

    // Sub-department dropdown options
    DEPARTMENTS: [
      { value: "raw-material",  label: "Raw Material Procurement" },
      { value: "rocket-motor",  label: "Rocket Motor Casing" },
    ],
  },

   /* -------- APP FOOTER -------- */
  APP_FOOTER: {
    COPYRIGHT:  "Copyright © 2026 Defence Research & Development Organisation (DRDO). All rights reserved.",
    CREDITS:    "Content & Maintenance - DRDO  |  Design & Development - Bharat Electronics Ltd.",
    BEL_LABEL:  "BEL",
    BEL_ALT:    "Bharat Electronics Limited",
  },

  /* -------- SYSTEM MANAGER DASHBOARD -------- */
  SYSTEM_MANAGER: {
    TITLE: "System Manager Dashboard",
    SUBTITLE: "Oversight and Administration of Blockchain Traceability System",

    KPI: {
      ACTIVE_USERS: "Active Users",
      OPEN_BATCHES: "Open Batches",
      PENDING_APPROVALS: "Pending Approvals",
      SYSTEM_SCORE: "System Integrity Score",
    },

    CHART_TITLE: "Monthly Activity by Division",

    TABS: {
      USERS: "User Accounts",
      CREATE_BATCH: "Create New Batch",
      RECENT_ACTIVITY: "Recent Activity",
    },

    TABLE: {
      NO_DATA: "No material records submitted yet",
      BATCH_ID: "Batch ID",
      PRODUCT_TYPE: "Product Type",
      PRODUCT_CODE: "Product Code",
      MATERIAL: "Material Type",
      CREATED_AT: "Created At",
    },

    BATCH_DETAILS: {
      MOTOR_ID: "Motor ID",
      MOTOR_TYPE: "Motor Type",
      BATCH_TYPE: "Batch Type",
      OVERALL_PROGRESS: "Overall Progress",
      DEPARTMENTS: "Departments",
      ASSIGNED_TO: "Assigned To",
      CREATED_ON: "Created On",
      BATCH_AGE: "Batch Age",
      RISK_LEVEL: "Risk Level",
      SUB_STAGES: "Sub-Stages",
      STATUS: "Status",
      PROGRESS: "Progress",
      DELAYED: "⚠ Delayed",
      HAS_FAILURES: "✕ Has Failures",
      PENDING_APPROVAL: "⧖ Pending Approval",
      NO_STAGE_DATA: "No stage data available.",
      NO_DATA_AVAILABLE: "No data available",
      COMPLETE: "% Complete",
      SUB_DEPT: {
        TITLE: "Sub-Department Details",
        SUBTITLE: "Workflow, quality, material and approval visibility",
        SNAPSHOT: "Snapshot",
        OVERVIEW: "Operational Overview",
        PROGRESS_INSIGHTS: "Progress Insights",
        QUALITY_INSIGHTS: "Quality Insights",
        WORKFLOW_AND_RISK: "Workflow & Risk",
        MATERIALS_SUMMARY: "Materials Summary",
        CASINGS_SUMMARY: "Casings Summary",
        PROCESSES_SUMMARY: "Processes Summary",
        SECTIONS_SUMMARY: "Sections Summary",
        INGREDIENTS_SUMMARY: "Ingredients Summary",
        OPERATIONS_SUMMARY: "Operations Summary",
        FIELDS_SUMMARY: "Fields Summary",
        ITEMS_SUMMARY: "Items Summary",
        SUBMISSION_INFO: "Submission Info",
        TIMELINE: "Timeline",
        DOCUMENTS: "Documents",
        READINESS: "Readiness",
        MATERIALS_TRACKED: "Materials Tracked",
        CASINGS_TRACKED: "Casings Tracked",
        PROCESSES_TRACKED: "Processes Tracked",
        SECTIONS_TRACKED: "Sections Tracked",
        INGREDIENTS_TRACKED: "Ingredients Tracked",
        OPERATIONS_TRACKED: "Operations Tracked",
        FIELDS_TRACKED: "Fields Tracked",
        ITEMS_TRACKED: "Items Tracked",
        TESTS_EXECUTED: "Tests Executed",
        TIMELINE_EVENTS: "Timeline Events",
        DOCUMENT_COUNT: "Documents",
        MATERIAL_FAILURES: "Material Failures",
        LAST_ACTIVITY: "Last Activity",
        FILLED_SPECS: "Filled Specs",
        COMPLETION: "Completion",
        MATERIALS: "Materials",
        TOTAL_TESTS: "Total Tests",
        PASSED: "Passed",
        FAILED: "Failed",
        PASS_RATE: "Pass Rate",
        SUB_DEPARTMENT_ID: "Sub-Department ID",
        DEPARTMENT_ID: "Department ID",
        CURRENT_STATUS: "Current Status",
        APPROVAL_STATE: "Approval State",
        SUBMISSION_STATE: "Submission State",
        SUBMITTED_BY: "Submitted By",
        SUBMITTED_ON: "Submitted On",
        APPROVED_BY: "Approved By",
        APPROVED_ON: "Approved On",
        REJECTED_BY: "Rejected By",
        REJECTED_ON: "Rejected On",
        READY_FOR_APPROVAL: "Ready For Approval",
        NOT_READY_FOR_APPROVAL: "Not Ready For Approval",
        ALL_LOTS_ENTERED: "All Lots Entered",
        LOTS_PENDING: "Lot Entry Pending",
        APPROVAL_PENDING: "Approval Pending",
        APPROVAL_NOT_PENDING: "Approval Not Pending",
        REWORK_REQUIRED: "Rework Required",
        NO_REWORK_REQUIRED: "No Rework Required",
        RESUBMISSIONS: "Resubmissions",
        NO_RISK_FACTORS: "No risk factors reported.",
        EMPTY_NOTICE: "Showing the full panel layout with placeholders until detail data is available.",
        ERROR_NOTICE: "Live detail data could not be loaded. Placeholder values are shown below.",
        REQUEST_RETRY: "Retry",
      },
    },
  },

  SOURCING: {
    TITLE: "Sourcing Department",
    HEADER_SUBTITLE: "Integrated system for recording initial data",
    SECTION_TITLES: {
      RAW_MATERIALS: (count) => `Raw Materials Pending (${count})`,
      ROCKET_CASINGS: (count) => `Rocket Casings Pending (${count})`,
      HISTORY: "Recent Session Activity",
    },
    TABLE_HEADERS: {
      BATCH_ID: "Batch ID",
      SOURCE: "Source Partner",
      QUANTITY: "Quantity",
      REPORT: "Report",
      SUBMITTED_BY: "Submitted By",
      ACTIONS: "Actions",
      DIMENSIONS: "Dimensions",
      WEIGHT: "Weight",
      MEDIA: "Media",
    },
    RAW_MATERIAL: {
      TITLE: "Raw Material Procurement",
      SHORT_DESCRIPTION: "Register new material lots, update partner details.",
      NEW_SUBMISSION: "New Submission",
      FORM_HEADER_CREATE_LOT_TITLE: "Create Lot",
      FORM_HEADER_CREATE_LOT_SUBTITLE: "Enter details to fill the lot details",
      STATS: {
        CREATED_LOTS: "Created Lots",
        PENDING_LOTS: "Pending Lots",
        WAITING_FOR_APPROVAL: "Waiting for Approval",
        APPROVED_LOTS: "Approved Lots",
        REJECTED_LOTS: "Rejected Lots",
      },
    },
    CASING: {
      TITLE: "Rocket Motor Casing Receipt", // Merged
      DESCRIPTION: "Store casing data received from sources and link reports & media.",
      MANDATORY: "(Mandatory)",
      SUBMIT: "Submit for Verification",
      LOG_TITLE: "Casing Submission Logs",
      NEW_SUBMISSION: "New Submission",
      CONTINUING_DRAFT: "Continuing Draft",
      FORM_HEADER_CREATE_MOTOR_CASING_TITLE: "Create Motor Casing",
      FORM_HEADER_CREATE_MOTOR_CASING_SUBTITLE: "Enter details to register a new motor casing",
      STATS: {
        CREATED_MOTORS: "Created Motors",
        PENDING_MOTORS: "Pending Motors",
        WAITING_FOR_APPROVAL: "Waiting for Approval",
        APPROVED_MOTORS: "Approved Motors",
        REJECTED_MOTORS: "Rejected Motors",
      },
    },
    BATCH_LIST: {
      RM_TITLE: "Raw material lots",
      MOTOR_TITLE: "Rocket Motor batch list",
      COL_BATCH_ID: "Batch ID",
      COL_MOTOR_CASING_ID: "Motor casing ID",
      COL_PROJECT_ID: "Project ID",
      COL_BATCH_TYPE: "Batch Type",
      COL_CASING_TYPE: "Casing type",
      COL_MOTOR_ID: "Motor ID",
      COL_MOTOR_STAGE: "Motor stage",
      COL_MOTOR_TYPE: "Motor Type",
      COL_INSULATION_TYPE: "Insulation type",
      COL_RECEIVING_DATE: "Receiving date",
      COL_MANAGER: "Manager",
      COL_CREATED_ON: "Created On",
      COL_PRIORITY: "Priority",
      COL_RM_STATUS: "RM Status",
      COL_STAGE_STATUS: "Stage Status",
      COL_LOT_ID: "Lot ID",
      COL_PROCUREMENT_ID: "Procurement ID",
      COL_MATERIAL_CODE: "Material",
      COL_MATERIAL_NAME: "Material name",
      COL_SUPPLY_ORDER: "Supply order",
      COL_RECEIPT_DATE: "Receipt date",
      COL_MANUFACTURER: "Manufacturer",
      COL_CREATED_BY: "Created by",
      CREATE_LOT: "Create Lot",
      CREATE_MOTOR_CASING: "Create Motor Casing",
      EDIT_LOT: "Edit",
      DELETE_LOT: "Delete",
      DELETE_LOT_TOOLTIP: "Delete lot (only while In Progress)",
      DELETE_CASING_TOOLTIP: "Delete casing form (only while In Progress)",
      MOTOR_TYPE_PREFIX: "Type ",
      UNASSIGNED: "Unassigned",
      FILL_ACTION: "Fill Specifications",
      CONTINUE_ACTION: "Continue Filling",
      EDIT_ACTION_TOOLTIP: "Load previously submitted data for editing",
      VIEW_LOT_DETAILS: "View lot details",
      VIEW_LOT_DETAILS_TOOLTIP: "View submitted lot specifications",
      LOT_DETAILS_TITLE: "Lot submission record",
      LOT_DETAILS_SUBTITLE: "Read-only view of submitted procurement and quality data",
      LOT_DETAILS_LOADING: "Loading lot details…",
      LOT_DETAILS_EMPTY: "No specification data recorded for this lot.",
      LOT_DETAILS_PROCUREMENT_SECTION: "Procurement details",
      LOT_DETAILS_SPEC_SECTION: "Quality specifications",
      LOT_DETAILS_CERTIFICATES_SECTION: "Certificates & attachments",
      LOT_DETAILS_NO_CERTIFICATES: "No certificates attached.",
      VIEW_CASING_DETAILS: "View casing details",
      VIEW_CASING_DETAILS_TOOLTIP: "View submitted motor casing record",
      CASING_DETAILS_TITLE: "Motor casing submission record",
      CASING_DETAILS_LOADING: "Loading casing details…",
      CASING_DETAILS_EMPTY: "No casing details available for this form.",
      CASING_DETAILS_IDENTIFICATION_SECTION: "Identification",
      CASING_DETAILS_SECTIONS: "Submitted sections",
      FILTERS_TOGGLE: "Filters",
      FILTERS_TITLE: "Refine lot list",
      FILTERS_MATERIAL: "Material",
      FILTERS_MANUFACTURER: "Manufacturer name",
      FILTERS_FROM_DATE: "From date",
      FILTERS_TO_DATE: "To date",
      FILTERS_STATUS: "Status",
      FILTERS_APPLY: "Apply filters",
      FILTERS_CLEAR: "Clear all",
      FILTERS_ALL_MATERIALS: "All materials",
      FILTERS_CLOSE_PANEL: "Close",
      FILTERS_TITLE_MOTOR: "Refine motor casing list",
      FILTERS_MOTOR_STAGE: "Motor stage",
      FILTERS_CASING_TYPE: "Casing type",
      FILTERS_INSULATION_TYPE: "Insulation type",
      FILTERS_ALL_STAGES: "All stages",
      FILTERS_ALL_CASING_TYPES: "All casing types",
      FILTERS_ALL_INSULATION: "All insulation types",
    },
    MESSAGES: {
      SUBMIT_SUCCESS: "Record submitted successfully",
      SUBMIT_ERROR: "Unable to submit record. Please try again.",
      PROCESSING: "Processing submission...",
      NO_RECORDS: "No records found",
    },
    COMMON_PROCESSES_FETCH_ERROR: "Unable to fetch process list. Please try again.",
    // New Approver Strings
    APPROVER_TITLE: "Sourcing Approval Authority",
    APPROVER_SUBTITLE: "Review and authenticate procurement records before Blockchain block creation.",

    // Specific Approval Messages
    APPROVE_SUCCESS: (type: string) => `${type.toUpperCase()} approved successfully`,
    REJECT_SUCCESS: (type: string) => `${type.toUpperCase()} rejected successfully`,
    PROCESS_ERROR: "Error processing approval action.",

    SPECIFICATION_FORM: {
      TITLE: "Quality Specifications",
      SUBTITLE: "Select materials, define quantities, and record analytical parameters.",
      CREATE_LOT_BUILDER_TITLE: "Create raw material lots",
      CREATE_LOT_BUILDER_SUBTITLE:
        "Add each material once, then add one or more lots per material. Supply order, receipt date, and manufacturer apply to the material; enter lot ID, analyzed results, remarks, and certificates per lot.",
      ADD_LOT: "Add lot",
      REMOVE_MATERIAL_TOOLTIP: "Remove material",
      REMOVE_LOT_TOOLTIP: "Remove lot",
      ALL_MATERIALS_ADDED: "All available materials have been added to the form.",
      LOT_LABEL: "Lot",
      SELECT_MATERIAL_LABEL: "Select Raw Material",
      SELECT_MATERIAL_PLACEHOLDER: "— Choose raw material —",
      LOADING_MATERIALS: "Loading materials...",
      ADD_TO_FORM: "Add to Form",
      EMPTY_ADDED_TITLE: "No materials added yet",
      EMPTY_ADDED_SUBTITLE: "Select a raw material above and click 'Add to Form' to begin",
      READY_TITLE: "Ready to submit for approval",
      READY_SUBTITLE: "Fill all analyzed results before submitting for approval. You can save as draft at any point and continue later.",
      NOT_READY_TITLE: "No materials added yet",
      NOT_READY_SUBTITLE: "Add at least one material and fill in some results to submit",
      SAVE_DRAFT: "Save as Draft",
      SUBMIT_APPROVAL: "Submit for Approval",
      RESUBMIT_APPROVAL: "Resubmit for Approval",
      SAVE_CONTINUE: "Save progress and continue later",
      MATERIALS_LOAD_FAILED: "Materials failed to load",
      MATERIALS_FETCH_ERROR: "An unexpected error occurred while fetching materials",
      SPECIFICATIONS_FETCH_ERROR: "Unable to fetch specifications for selected material",
      SPECIFICATIONS_NOT_FOUND: "Specifications not found for selected material",
      DRAFT_SAVED_SUCCESS: "Draft saved successfully. You can continue later.",
      SUBMIT_SUCCESS: "Specifications submitted for approval.",
      DETAILS_FETCH_ERROR: "Unable to load existing form details. Please try again.",
      FORM_ID_MISSING: "Unable to continue. Form ID is missing for this batch.",
      BATCH_ID_MISSING: "Unable to create form. Batch ID is missing.",
      SUB_DEPARTMENT_MISSING: "Unable to proceed. Sub-department context is missing.",
      EMPTY_FORM_ERROR: "Add at least one material and specification before saving.",
      CREATE_FAILED: "Failed to create raw material procurement form.",
      UPDATE_FAILED: "Failed to update raw material procurement form.",
      DETAILS_NOT_FOUND: "No saved form data found for this submission.",
      CREATE_DRAFT_SUCCESS: "Raw material procurement draft created successfully.",
      CREATE_SUBMIT_SUCCESS: "Raw material procurement submitted for approval successfully.",
      UPDATE_DRAFT_SUCCESS: "Raw material procurement draft updated successfully.",
      UPDATE_SUBMIT_SUCCESS: "Raw material procurement updated for approval successfully.",
      EDIT_MODE_BANNER: "You are editing a rejected submission. Previously submitted values are pre-loaded. Review and correct before resubmitting.",
      SPEC_STATUS_OUT_OF_RANGE: "Out of Range",
      BLOCK_LABEL: "Block",
      SPECIFICATION_LABEL: "specification",
      SPECIFICATION_LABEL_PLURAL: "specifications",
      RESULTS_FILLED_SUFFIX: "filled",
      RESULTS_ENTERED_SUFFIX: "results entered",
      MATERIAL_SUFFIX: "material",
      MATERIAL_SUFFIX_PLURAL: "materials",
      BLOCK_SUFFIX: "Block",
      BLOCK_SUFFIX_PLURAL: "Blocks",
      LOT_SUFFIX: "lot",
      LOT_SUFFIX_PLURAL: "lots",
      SAVE_DISABLED_TOOLTIP: "Add at least one material to save",
      SUBMIT_DISABLED_TOOLTIP: "Complete all required fields and analyzed results before saving or submitting",
      ADDING_TO_FORM: "Adding...",
      REMOVE_BLOCK_TOOLTIP: "Remove this block",
      LOT_PLACEHOLDER: "e.g. LOT-2024-01",
      LOT_ID_LOCKED_HINT: "Lot ID cannot be changed when updating an existing lot",
      ANALYZED_RESULT_PLACEHOLDER: "Enter value",
      REMARKS_PLACEHOLDER: "Add remarks...",
      SPEC_COUNT_SUFFIX: "specs",
      SUPPLY_ORDER_LABEL: "Supply order no.",
      RECEIPT_DATE_LABEL: "Receipt date",
      MANUFACTURER_LABEL: "Manufacturer",
      FIELD_REQUIRED_SUPPLY_ORDER: "Supply order no. is required",
      FIELD_REQUIRED_RECEIPT_DATE: "Receipt date is required",
      FIELD_REQUIRED_MANUFACTURER: "Manufacturer is required",
      FIELD_REQUIRED_LOT_ID: "Lot ID is required",
      MANDATORY_FIELDS_PENDING:
        "Complete all required fields (supply order, receipt date, manufacturer, lot ID) and fill every analyzed result before saving or submitting.",
      FIELD_REQUIRED_ANALYZED_RESULT: "Analyzed result is required",
      CERTIFICATES_TITLE: "Certificates",
      CERTIFICATES_SUBTITLE: "Upload PDF, Office, images, or ZIP. Multiple files allowed.",
      CERT_FILE_NAME: "File name",
      CERT_TYPE: "Certificate type",
      UPLOAD_CERTIFICATES: "Upload files",
      ADD_MORE_CERTIFICATES: "Add more files",
      OPEN_CERT_LINK: "Open link",
      REMOVE_CERTIFICATE: "Remove",
      CERT_INVALID_FILE: "Invalid file type. Use PDF, Word, Excel, images, or ZIP.",
      TABLE_HEADERS: {
        MATERIAL: "Material",
        LOT_ID: "Lot ID",
        LOT_BATCH_NO: "Man. Lot/Batch No.",
        SPECIFICATION: "Specification",
        REF_RANGE: "Ref. Range",
        ANALYZED_RESULT: "Analyzed Result",
        REMARKS: "Remarks",
      },
      CONFIRM_DRAFT_TITLE: "Save as Draft?",
      CONFIRM_DRAFT_MESSAGE: "Your progress will be saved. You can return and continue filling the form later. The batch status will be marked as 'In Progress'.",
      CONFIRM_DRAFT_ACTION: "Save Draft",
      CONFIRM_DRAFT_CANCEL_ACTION: "Cancel",
      DELETE_LOT: "Delete Lot",
      DELETE_LOT_TOOLTIP: "Permanently remove this lot from the list",
      CONFIRM_DELETE_TITLE: "Delete lot?",
      CONFIRM_DELETE_MESSAGE:
        "This lot will be soft-deleted and removed from your list. Only lots with an 'In Progress' status can be deleted. This action cannot be undone.",
      CONFIRM_DELETE_ACTION: "Delete Lot",
      DELETE_SUCCESS: "Raw material lot deleted successfully",
      DELETE_FAILED: "Failed to delete lot. Please try again.",
      DELETE_NOT_ALLOWED: "Only lots with an 'In Progress' status can be deleted.",
      CONFIRM_SUBMIT_TITLE: "Submit for Approval?",
      CONFIRM_RESUBMIT_TITLE: "Resubmit for Approval?",
      CONFIRM_SUBMIT_MESSAGE: "Once submitted, you will not be able to edit this form until the approver takes action. Make sure all data is accurate.",
      CONFIRM_RESUBMIT_MESSAGE: "You are resubmitting a previously rejected entry. Ensure all corrections have been made. This will be sent to the approver for review.",
      CONFIRM_RESUBMIT_ACTION: "Resubmit",
      CONFIRM_SUBMIT_ACTION: "Submit",
      CONFIRM_CANCEL_ACTION: "Go Back",
      UNSAVED_BACK_TITLE: "Unsaved changes detected",
      UNSAVED_BACK_MESSAGE: "You have unsaved changes. Save as draft to avoid losing your data.",
      UNSAVED_BACK_CONFIRM: "Go back to Form",
      UNSAVED_BACK_DISCARD: "Discard Changes",
      LOT_NO: "Lot No",
      PARAMETER: "Parameter",
      RANGE: "Range",
      RESULT: "Result",
      REMARKS: "Remarks"
    },
    CASING_FORM: {
      TITLE: "Casing Verification Overview",
      SUBTITLE: "Review casing dimensional data and material proofing",
      READY_TO_SUBMIT: "Ready to submit for approval",
      NOT_READY_TO_SUBMIT: "Select project, motor stage, and enter motor ID to save or submit.",
      ACTION_HELPER: "Save or submit once identification is complete. Other sections can be filled in later.",
      SAVE_TOOLTIP: "Save progress and continue later",
      SAVE_DRAFT: "Save as Draft",
      SUBMIT_APPROVAL: "Submit for Approval",
      RESUBMIT_APPROVAL: "Resubmit for Approval",
      MOTOR_ID: "Motor ID",
      MOTOR_CASING_ID: "Motor casing ID",
      MOTOR_CASING_ID_PH: "e.g. RMC-A1-2026-0001",
      MOTOR_STAGE: "Motor stage",
      MOTOR_STAGE_PH: "A–G",
      MOTOR_NO: "Motor no.",
      MOTOR_NO_PH: "e.g. 1",
      MOTOR_ID_PH: "Enter Motor ID or reference number…",
      API_IDENTIFICATION: "Motor casing identification",
      ITEMS_RECEIVED: "Items received (with motor)",
      ITEMS_DESCRIPTION: "Description",
      ITEMS_DIMENSION: "Dimension",
      ITEMS_UNIT: "Unit",
      CLEARANCE_REPORT: "Motor Clearance Report",
      CLEARANCE_REPORT_PH: "Enter clearance report reference or number…",
      INSULATION_REPORT: "Insulation Clearance Report",
      TENSILE_STRENGTH: "Tensile Strength",
      ELONGATION: "Elongation",
      EROSION_RATE: "Erosion Rate",
      THERMAL_CONDUCTIVITY: "Thermal Conductivity",
      UT_NDT: "UT / NDT Report",
      WAIVERS: "Waivers if Any",
      WAIVERS_PH: "Enter waiver reference or description (if applicable)…",
      VISUAL_OBS: "Visual Observation",
      VISUAL_OBS_DESC: "Upload images or video of the visual observation (JPG, PNG, WEBP, MP4, WEBM · max 50MB)",
      MEDIA_ON_FILE_PREFIX: "Media reference on file:",
      DIMENSIONAL_REPORT: "Dimensional Inspection Report",
      EDIT_MODE_WARNING: "You are editing a rejected submission. Previously submitted values are pre-loaded. Review and correct all fields before resubmitting.",
      FOOTER_NOTE: "All clearance report fields must be completed before submission. Dimensional inspection values are auto-loaded based on motor type. Waivers are optional.",
      DETAILS_LABEL: "Details",
      DETAILS_PH: "Enter details…",
      REMARKS_LABEL: "Remarks",
      REMARKS_PH: "Add remarks…",
      EMPTY_DIM_TITLE: "No motor type selected",
      EMPTY_DIM_SUBTITLE: "Select a batch to load dimensional parameters",
      DIM_COL_TB: "T - B",
      DIM_COL_RL: "R - L",
      DIM_COL_TLBR: "TL - BR",
      DIM_COL_TRBL: "TR - BL",
      DIM_COL_REMARKS: "Remarks",
      PARAMETERS_SUFFIX: "parameters",
      MOTOR_TYPE_CHIP_PREFIX: "Motor Type ",
      SUB_FIELDS: "sub-fields",
      MANDATORY: "Mandatory",
      DETAILS_FETCH_ERROR: "Unable to load existing casing form details. Please try again.",
      DETAILS_NOT_FOUND: "No saved casing form data found for this submission.",
      FORM_ID_MISSING: "Motor casing ID is missing for this record.",
      BATCH_ID_MISSING: "Motor casing ID is required before saving this form.",
      SUB_DEPARTMENT_MISSING: "Unable to proceed. Sub-department context is missing.",
      CREATE_FAILED: "Failed to create rocket motor casing form.",
      UPDATE_FAILED: "Failed to update rocket motor casing form.",
      FORM_ALREADY_EXISTS: "A casing form already exists for this batch. Please continue from existing form.",
      INVALID_STATE_UPDATE: "Form cannot be updated in current status.",
      INVALID_PARAM_ID: "One or more dimensional parameter IDs are invalid for this motor type.",
      INVALID_MOTOR_TYPE: "Invalid motor type. Please choose A, B, C or D.",
      DIMENSIONAL_PARAMS_FETCH_ERROR: "Unable to fetch dimensional inspection parameters.",
      LOADING_FORM_DETAILS: "Loading casing form details…",
      LOADING_MOTOR_PARAMS: "Loading dimensional parameters for the selected motor stage…",
      FORM_NOT_FOUND: "No casing form found for the provided form ID.",
      CREATE_DRAFT_SUCCESS: "Casing details saved as draft successfully.",
      CREATE_SUBMIT_SUCCESS: "Casing details submitted for approval successfully.",
      UPDATE_DRAFT_SUCCESS: "Rocket motor casing draft updated successfully.",
      UPDATE_SUBMIT_SUCCESS: "Rocket motor casing updated for approval successfully.",
      CONFIRM_DRAFT_TITLE: "Save as Draft?",
      CONFIRM_DRAFT_MESSAGE: "Your casing form progress will be saved. You can return and continue later. The batch will be marked as 'In Progress'.",
      CONFIRM_DRAFT_ACTION: "Save Draft",
      CONFIRM_DRAFT_CANCEL_ACTION: "Cancel",
      CONFIRM_SUBMIT_TITLE: "Submit for Approval?",
      CONFIRM_RESUBMIT_TITLE: "Resubmit for Approval?",
      CONFIRM_SUBMIT_MESSAGE: "Once submitted, you cannot edit this form until the approver takes action. Confirm all data is accurate.",
      CONFIRM_RESUBMIT_MESSAGE: "You are resubmitting a rejected entry. Ensure all corrections are made. This will be forwarded to the approver.",
      CONFIRM_SUBMIT_ACTION: "Submit",
      CONFIRM_RESUBMIT_ACTION: "Resubmit",
      CONFIRM_CANCEL_ACTION: "Go Back",
      UNSAVED_BACK_TITLE: "Unsaved changes detected",
      UNSAVED_BACK_MESSAGE: "You have unsaved changes. Save as draft to avoid losing your data.",
      UNSAVED_BACK_CONFIRM: "Go back to Form",
      UNSAVED_BACK_DISCARD: "Discard Changes",
      DELETE_CASING: "Delete",
      DELETE_CASING_TOOLTIP: "Delete casing form (only while In Progress)",
      CONFIRM_DELETE_TITLE: "Delete casing form?",
      CONFIRM_DELETE_MESSAGE:
        "This casing form will be soft-deleted and removed from your list. Only forms with an 'In Progress' status can be deleted. This action cannot be undone.",
      CONFIRM_DELETE_ACTION: "Delete Casing",
      DELETE_SUCCESS: "Rocket motor casing record deleted successfully",
      DELETE_FAILED: "Failed to delete casing form. Please try again.",
      DELETE_NOT_ALLOWED: "Only casing forms with an 'In Progress' status can be deleted."
    },
    CASING_CREATE: {
      TITLE: "Motor Casing Receipt",
      SUBTITLE: "Enter motor casing details per receipt, inspection, and weighment format",
      SECTION_IDENTIFICATION: "Identification",
      PROJECT: "Project name",
      MOTOR_STAGE: "Rocket motor name / stage",
      MOTOR_NO: "Motor no.",
      MOTOR_ID: "Motor ID",
      MOTOR_ID_PH: "e.g. RMC-A1-2026-0001",
      MOTOR_CASING_ID: "Motor casing ID",
      MOTOR_CASING_ID_AUTO: "Assigned automatically after save",
      SECTION_MOTOR_RECEIPT: "1. Motor Receipt",
      CASING_TYPE: "Casing type",
      RECEIVING_DATE: "Receiving date",
      ITEMS_RECEIVED: "Items received with motor",
      RUBBER_SHEET: "Rubber sheet",
      DIMENSION: "Dimension",
      UNIT: "Unit",
      RECEIPT_STATUS: "Received / not received",
      OBSERVATIONS: "Observations / waiver",
      SECTION_CLEARANCES: "A. Clearances & reports",
      GREEN_CARD_STATUS: "Green card",
      GREEN_CARD_NO: "Green card no.",
      CLEARANCE_DATE: "Clearance date",
      CLEARANCE_AUTHORITY: "Clearance authority",
      CLEARANCE_DETAILS: "Details & observations",
      SECTION_INSULATION: "B. Rubber insulation lining report",
      CURING_DATE: "Date of insulation curing",
      INSULATION_TYPE: "Insulation type",
      REPORT_NO: "Rubber properties report no.",
      INSULATION_RECEIPT: "Report received / not received",
      REPORT_UPLOAD: "Upload report",
      UPLOADED_FILE_LABEL: "Uploaded file",
      CHANGE_FILE: "Change file",
      REMOVE_FILE: "Remove",
      OPEN_FILE: "Open file",
      PENDING_UPLOAD_HINT: "Saved with this form. Choose a new file below to replace it.",
      ADD_MEDIA: "Tap to attach an image or video",
      REPLACE_MEDIA: "Replace with another file",
      CANCEL_REPLACE: "Cancel",
      MECH_PROPERTIES: "Rubber mechanical properties",
      THERMAL_PROPERTIES: "Rubber thermal properties",
      REPORTED: "Reported",
      ACEM_SPEC: "Spec @ ACEM",
      SECTION_NDT: "C. NDT / UT report",
      POST_PPT_UT: "Date of post PPT UT",
      NDT_DATE: "Date of NDT",
      NDT_OBSERVATIONS: "Observations (NDT & post PPT UT)",
      ACEM_NDT: "D. ACEM NDT observations",
      PROJECT_RUBBER: "E. Project rubber surface observations",
      OTHER_DETAILS: "Other details",
      SECTION_VISUAL: "2. Visual inspection",
      COL_SR: "Sr.",
      COL_DESCRIPTION: "Description",
      COL_OBSERVATIONS: "Observations",
      COL_REMARK: "Remark",
      COL_MEDIA: "Image / video",
      SECTION_WEIGHMENT: "3. Weighment details",
      WEIGHT_WITHOUT: "Weight without harness (kg)",
      WEIGHT_WITH: "Weight with harness (kg)",
      WEIGHSCALE: "Weighscale details",
      CALIBRATION_DUE: "Calibration due date",
      SECTION_DIMENSIONAL: "4. Dimensional inspection",
      SECTION_MOCK_TRIAL: "5. Mock trial",
      COL_SPEC: "Specified dim",
      COL_R2T: "R2T–R2B",
      COL_R1R: "R1R–R1L",
      COL_TL: "TL–BR",
      COL_TR: "TR–BL",
      COL_R2T_SHORT: "R2T",
      COL_R2B_SHORT: "R2B",
      COL_R1R_SHORT: "R1R",
      COL_R1L_SHORT: "R1L",
      COL_TL_SHORT: "TL",
      COL_BR_SHORT: "BR",
      COL_TR_SHORT: "TR",
      COL_BL_SHORT: "BL",
      COL_ARC_LENGTH: "ARC length",
      COL_AXIAL_LENGTH: "Axial length",
      RECEIVED: "Received",
      NOT_RECEIVED: "Not received",
      COMPOSITE: "Composite",
      METALLIC: "Metallic",
      ROCASIN: "Rocasin",
      EPDM: "EPDM",
      SELECT_PROJECT: "Select project",
      SELECT_STAGE: "Select motor stage",
      SELECT_MOTOR_NO: "Select motor no.",
      IDENTIFICATION_GATE_HINT:
        "Select a project, motor stage, and enter motor ID to unlock receipt, inspection, and remaining steps.",
      STEP_IDENTIFICATION_RECEIPT: "Identification & receipt",
      STEP_VISUAL: "Visual inspection",
      STEP_WEIGHMENT: "Weighment",
      STEP_DIMENSIONAL: "Dimensional inspection",
      STEP_MOCK_TRIAL: "Mock trial",
      MOCK_TRIAL_SELECT_STAGE: "Select a motor stage to load the mock trial form.",
      STEP_OF: "Step {current} of {total}",
      BACK: "Back",
      NEXT: "Next",
      COMPLETE_ALL_STEPS: "Complete all steps to enable Save as Draft and Submit.",
    }
  },

  USER_BATCH_LIST: {
    SEARCH_PLACEHOLDER: "Search…",
    SHOWING: "Showing",
    OF: "of",
    RECORDS: "records",
    NO_RECORDS: "No records found",
    EMPTY_SUBTITLE: "Try adjusting the search or filters above",
    DEFAULT_LABEL: "Batch list",
    COL_ACTION: "Action",
    COL_HASH: "#",
    FILTER_ALL: "All",
  },

  ERRORS: {
    FETCH_LOGS: "Error occurred while fetching casing data.",
    SUBMISSION_FAILED: "Submission failed. Please check your connection.",
    REQUIRED_FIELDS: "Please fill in all mandatory details.",
  },

  MANUFACTURING: {
    TITLE: "Propellant Manufacturing",
    DEPARTMENT_NAME: "Manufacturing Department",
    HEADER_SUBTITLE: "Select a process below to view detailed information and manage its operations.",

    // ── Shared Batch List Strings ────────────────────────────────────────────
    BATCH_LIST: {
      COL_BATCH_ID: "Batch ID",
      COL_BATCH_TYPE: "Batch Type",
      COL_MOTOR_ID: "Motor ID",
      COL_MOTOR_TYPE: "Motor Type",
      COL_MOTOR_STAGE: "Motor Stage",
      COL_TYPE: "Type",
      COL_MANAGER: "Manager",
      COL_CREATED_ON: "Created On",
      COL_PRIORITY: "Priority",
      MOTOR_TYPE_PREFIX: "Type ",
      UNASSIGNED: "Unassigned",
      FILL_ACTION: "Fill Specifications",
      CONTINUE_ACTION: "Continue Filling",
      EDIT_ACTION: "Edit & Resubmit",
      EDIT_ACTION_TOOLTIP: "Load previously submitted data for editing",
      FILTERS_TOGGLE: "Filters",
      FILTERS_TITLE: "Refine batch list",
      FILTERS_PRIORITY: "Priority",
      FILTERS_STATUS: "Status",
      FILTERS_MOTOR_ID: "Motor ID",
      FILTERS_LOT_ID: "Lot ID",
      FILTERS_ALL_PRIORITIES: "All priorities",
      FILTERS_APPLY: "Apply filters",
      FILTERS_CLEAR: "Clear all",
      FILTERS_CLOSE_PANEL: "Close",
    },

    // ── Form Header Strings ─────────────────────────────────────────────────
    FORM_HEADER: {
      BACK_TO_LIST: "Back to List",
      NEW_SUBMISSION: "New Submission",
      EDITING_REJECTED: "Editing Rejected Submission",
      REJECTION_REASON: "Rejection Reason",
    },

    // ── Sub-Department Specific ──────────────────────────────────────────────
    RAW_MATERIAL_PREP: {
      TITLE: "Raw Material Preparation",
      COL_MATERIAL_TYPE: "Material Type",
      COL_RM_STATUS: "RM Status",
      TABLE_LABEL: "Raw material preparation batch list",
      EMPTY_TEXT: "No raw material preparation batches found",
      NEW_LABEL: "New Submission",
      EDIT_MODE_BANNER: "You are editing a rejected submission. Previously submitted values are pre-loaded. Review and correct before resubmitting.",
      BATCH_SCALE_LABEL: "Process for",
      PREMIX_LABEL: "Select Premix",
      PREMIX_PLACEHOLDER: "Choose premix",
      PROCESS_LABEL: "Select Process",
      PROCESS_PLACEHOLDER: "Choose process",
      SELECT_RAW_MATERIAL_LABEL: "Select Raw Material",
      SELECT_RAW_MATERIAL_PLACEHOLDER: "— Choose raw material —",
      SELECT_GRADE_LABEL: "Select Grade",
      SELECT_GRADE_PLACEHOLDER: "— Choose grade —",
      LOADING_MATERIALS: "Loading materials…",
      SELECT_PREMIX_AND_PROCESS: "Select a premix and process to load the form",
      NO_PROCESS_SELECTED_TITLE: "No process selected",
      NO_PROCESS_SELECTED_SUBTITLE:
        "Choose a premix, select process(es), and pick a raw material to load the form builder",
      TYPE_SELECTOR_LABEL: "Raw Material Type",
      TYPE_SELECTOR_NEW_HINT: "(select all that apply)",
      TYPE_SELECTOR_EDIT_HINT: "(locked to original selection)",
      SELECT_AT_LEAST_ONE: "Select a premix and process to continue",
      LOCK_EXPLANATION: "Delete all sections inside a builder first to change process.",
      NO_TYPE_SELECTED_TITLE: "No process selected",
      NO_TYPE_SELECTED_SUBTITLE: "Select a premix and process above to load the form builder",
      MATERIAL_SOLID: "Solid",
      MATERIAL_LIQUID: "Liquid",
      MATERIAL_LINEAR: "Linear",
      MATERIAL_ALL: "All Types",
      MATERIAL_SOLID_LIQUID: "Solid + Liquid",
      MATERIAL_SOLID_LINEAR: "Solid + Linear",
      MATERIAL_LIQUID_LINEAR: "Liquid + Linear",
      DETAILS_FETCH_ERROR: "Unable to load existing form details. Please try again.",
      DETAILS_NOT_FOUND: "No saved form data found for this submission.",
      FORM_ID_MISSING: "Unable to continue. Form ID is missing for this batch.",
      BATCH_ID_MISSING: "Unable to create form. Batch ID is missing.",
      SUB_DEPARTMENT_MISSING: "Unable to proceed. Sub-department context is missing.",
      EMPTY_FORM_ERROR: "Add at least one value before saving or submitting.",
      SCHEMA_LOAD_REQUIRED:
        "All premix forms must load their schema successfully before saving or submitting.",
      DELETE_PREMIX_TOOLTIP: "Remove this premix",
      WEIGHTMENT_SHEET_TITLE: "Weightment Sheet for Dispatch of Material to Mixing Station",
      WEIGHTMENT_SHEET_SUBTITLE: "Common for all premixes — record transferred weights before dispatch",
      WEIGHTMENT_MIXER_BUILDING: "Mixer Building Number",
      WEIGHTMENT_ADD_ROW: "Add Row",
      WEIGHTMENT_EMPTY_TITLE: "No weightment entries yet",
      WEIGHTMENT_EMPTY_SUBTITLE: "Add a row to record material weights transferred to the mixing station",
      WEIGHTMENT_COMPARE_LABEL: "Compare with identification sheet",
      WEIGHTMENT_DEVIATION_FOUND: "Deviation found",
      WEIGHTMENT_DEVIATION_MESSAGE: "Deviation message",
      CREATE_FAILED: "Failed to create raw material preparation form.",
      UPDATE_FAILED: "Failed to update raw material preparation form.",
      CREATE_DRAFT_SUCCESS: "Raw material preparation saved as draft successfully.",
      CREATE_SUBMIT_SUCCESS: "Raw material preparation submitted for approval successfully.",
      UPDATE_DRAFT_SUCCESS: "Raw material preparation draft updated successfully.",
      UPDATE_SUBMIT_SUCCESS: "Raw material preparation updated successfully.",
      UNSAVED_BACK_TITLE: "Unsaved changes detected",
      UNSAVED_BACK_MESSAGE: "You have unsaved raw material preparation changes. Save as draft to avoid losing your data.",
      UNSAVED_BACK_CONFIRM: "Go back to Form",
      UNSAVED_BACK_DISCARD: "Discard Changes",
    },
    CASE_PREP: {
      TITLE: "Case Preparation",
      COL_TREATMENT_TYPE: "Treatment Type",
      COL_CP_STATUS: "CP Status",
      COL_OPERATION_STATUS: "Operation Status",
      TABLE_LABEL: "Case preparation batch list",
      EMPTY_TEXT: "No case preparation batches found",
      NEW_LABEL: "New Submission",
      EDIT_MODE_BANNER: "You are editing a rejected submission. Previously submitted values are pre-loaded. Review and correct before resubmitting.",
      FORM_TITLE: "Case Preparation",
      FORM_SUBTITLE: "General activities and linear coating operation records",
      SECTION_GA_TITLE: "General Activities",
      SECTION_GA_SUBTITLE: "Surface inspection, abrading, cleaning and preheating steps",
      SECTION_LCO_TITLE: "Linear Coating Operation",
      SECTION_LCO_SUBTITLE: "Coating inspection, temperature, premix and application parameters",
      ALL_FILLED: "All filled",
      FILLED_SUFFIX: "filled",
      DETAILS_FETCH_ERROR: "Unable to load existing case preparation form details. Please try again.",
      DETAILS_NOT_FOUND: "No saved case preparation form data found for this submission.",
      FORM_ID_MISSING: "Unable to continue. Form ID is missing for this batch.",
      BATCH_ID_MISSING: "Unable to create form. Batch ID is missing.",
      SUB_DEPARTMENT_MISSING: "Unable to proceed. Sub-department context is missing.",
      EMPTY_FORM_ERROR: "Add at least one value before saving or submitting.",
      CREATE_FAILED: "Failed to create case preparation form.",
      UPDATE_FAILED: "Failed to update case preparation form.",
      CREATE_DRAFT_SUCCESS: "Case preparation form saved as draft successfully.",
      CREATE_SUBMIT_SUCCESS: "Case preparation form submitted for approval successfully.",
      UPDATE_DRAFT_SUCCESS: "Case preparation form saved as draft successfully.",
      UPDATE_SUBMIT_SUCCESS: "Case preparation form resubmitted for approval successfully.",
      UNSAVED_BACK_TITLE: "Unsaved changes detected",
      UNSAVED_BACK_MESSAGE: "You have unsaved case preparation changes. Save as draft to avoid losing your data.",
      UNSAVED_BACK_CONFIRM: "Go back to Form",
      UNSAVED_BACK_DISCARD: "Discard Changes",
      TREATMENT_CLEANING: "Cleaning",
      TREATMENT_SURFACE: "Surface Treatment",
      TREATMENT_FULL: "Full Process",
      TREATMENT_COATING: "Coating",
      TREATMENT_NOT_SELECTED: "Not Selected Yet",
      PLACEHOLDER_MOTOR_CASE_ID_1: "e.g. MC-001",
      PLACEHOLDER_MOTOR_CASE_ID_2: "e.g. MC-002",
      PLACEHOLDER_MOTOR_NO_1: "e.g. MN-001",
      PLACEHOLDER_MOTOR_NO_2: "e.g. MN-002",
      MOTOR_COUNT_LABEL: "No. of Motor(s)",
      MOTOR_COUNT_PLACEHOLDER: "Select count",
      MOTOR_ID_LABEL: "Select Motor Id",
      MOTOR_ID_PLACEHOLDER: "Select motor",
      PRRC_CLEARANCE_DATE_LABEL: "PRRC Clearance Date",
      PRRC_CLEARANCE_DATE_PLACEHOLDER: "DD/MM/YYYY",
      ADD_MOTORS_ACTION: "Add",
      NON_MAIN_BATCH_MESSAGE: "Case preparation form for this batch type is not available yet.",
      MOTOR_NAV_TITLE: "Motor Navigation",
      MOTOR_NAV_HINT: "Click a motor tab below to open its processing log and continue filling details.",
      MOTOR_CARD_TITLE: "Motor",
      DELETE_MOTOR_TOOLTIP: "Remove motor",
      SCHEMA_LOADING: "Loading case preparation schema...",
      SCHEMA_LOAD_ERROR: "Unable to load case preparation schema. Please try again.",
    },
    MIXING: {
      TITLE: "Mixing",
      COL_MIX_TYPE: "Mix Type",
      COL_MX_STATUS: "MX Status",
      COL_OPERATION_STATUS: "Operation Status",
      TABLE_LABEL: "Mixing batch list",
      EMPTY_TEXT: "No mixing batches found",
      NEW_LABEL: "New Submission",
      FORM_TITLE: "Mixing",
      FORM_SUBTITLE: "Record premix and final mix stage details",
      STAGE_PREMIX: "Premix",
      STAGE_FINAL_MIX: "Final Mix",
      MIXING_STAGE_LABEL: "Mixing Stage",
      MIXING_STAGE_PLACEHOLDER: "Select mixing stage",
      STAGE_NO_PLACEHOLDER: "Select number",
      LABEL_FINAL_MIX_NO: "Select Final Mix No.",
      ADD_CARD: "Add",
      SECTION_PREMIX_CARDS: "Premix",
      SECTION_FINAL_MIX_CARDS: "Final Mix",
      SECTION_TAB_PREMIX: "Premix",
      SECTION_TAB_FINAL_MIX: "Final Mix",
      NAV_BACK: "Back",
      NAV_NEXT: "Next",
      PREMIX_NAV_TITLE: "Premix Navigation",
      FINAL_MIX_NAV_TITLE: "Final Mix Navigation",
      PREMIX_NAV_HINT: "Click any premix tab below to open that premix card and continue filling its details.",
      FINAL_MIX_NAV_HINT: "Click any final mix tab below to open that card and continue filling its details.",
      PREMIX_COUNTER: "Premix {current} of {total}",
      FINAL_MIX_COUNTER: "Final Mix {current} of {total}",
      NO_PREMIX_CARDS: "No premix cards added yet. Select mixing stage and premix number above, then click Add.",
      NO_FINAL_MIX_CARDS: "No final mix cards added yet. Select mixing stage and final mix number above, then click Add.",
      REMOVE_CARD_TOOLTIP: "Remove this card",
      SECTION_PREMIX_STAGE: "Premix Stage",
      LABEL_PREMIX_NO: "Select Premix No.",
      LABEL_MIXER_BLDG: "Select Mixer & Bldg No.",
      LABEL_BOWL_ID: "Select Bowl Id",
      LABEL_BOWL_TRIAL_DATE: "Bowl Trial Date",
      LABEL_BOWL_TRIAL_OBS: "Bowl Trial Date & Observations",
      LABEL_PREMIX_DATE: "Premix Date",
      LABEL_PREMIX_QTY: "Premix Quantity",
      LABEL_MIXING_CYCLE: "Select the mixing cycle",
      LABEL_FINAL_MIX_CYCLE: "Select the final mix cycle",
      PLACEHOLDER_FINAL_MIX_CYCLE: "Choose final mix cycle",
      SECTION_FINAL_MIX_STAGE: "Final Mix Stage",
      SECTION_PROCESS_PARTICULARS: "Process Particulars",
      SECTION_PROCESS_PARTICULARS_HINT: "Fields are loaded from the selected mixing cycle (refer annexure).",
      PROCESS_PARTICULARS_EMPTY: "Choose a mixing cycle above to load process particulars.",
      SECTION_QUALITY_CHECKS: "Quality Checks",
      COL_PARAMETER: "Parameter",
      COL_SPECIFICATION: "Specification",
      COL_OBSERVED_VALUES: "Observed Values",
      COL_OBSERVED_READING: "Reading",
      PLACEHOLDER_MIXER_BLDG: "Choose mixer & building no.",
      PLACEHOLDER_BOWL_ID: "Choose bowl id",
      PLACEHOLDER_BOWL_TRIAL_OBS: "Enter bowl trial observations...",
      PLACEHOLDER_PREMIX_QTY: "Enter premix quantity",
      PLACEHOLDER_MIXING_CYCLE: "Choose mixing cycle",
      PLACEHOLDER_RPM: "Enter rpm",
      PLACEHOLDER_TIME: "Enter min",
      PLACEHOLDER_TEMP: "Enter °C",
      PLACEHOLDER_VACUUM: "Enter torr",
      PLACEHOLDER_OBSERVED_VALUE: "Enter value",
      PLACEHOLDER_SPEC_NA: "Not specified",
      COL_OPERATION: "Operation",
      COL_ROTATION: "Rotation (rpm)",
      COL_TIME: "Time (min)",
      COL_TEMP: "Temp (°C)",
      COL_VACUUM: "Vacuum (torr)",
      FINAL_MIX_PLACEHOLDER: "Final mix form fields will be added in a follow-up release.",
      SECTION_PRE_TITLE: "Pre-Mixing",
      SECTION_PRE_SUBTITLE: "Ingredient addition and mixing stages before final mix",
      SECTION_FINAL_TITLE: "Final Mixing",
      SECTION_FINAL_SUBTITLE: "TDI addition and viscosity sampling",
      ADD_OPERATION_ROW: "Add Operation Row",
      ALL_FILLED: "All filled",
      FILLED_SUFFIX: "filled",
      OPERATION_PLACEHOLDER: "Enter operation...",
      REMOVE_ROW_TOOLTIP: "Remove row",
      MIX_TYPE_COMPOSITE: "Composite",
      MIX_TYPE_SOLID: "Solid",
      MIX_TYPE_LIQUID: "Liquid",
      MIX_TYPE_NOT_SELECTED: "Not Selected Yet",
      PRE_ROW_1: "Addition of Ingredients 1 and 2 and mixing",
      PRE_ROW_2: "Addition of Ingredient 3 and mixing",
      PRE_ROW_3: "Addition of Ingredients 4 and mixing",
      PRE_ROW_4: "Addition of Ingredients 5 and mixing",
      PRE_SAMPLING_ROW: "Sampling for Homogeneity and Moisture analysis",
      FINAL_ROW_1: "Addition of TDI and Mixing",
      FINAL_ROW_2: "Sample for Viscosity",
      DETAILS_FETCH_ERROR: "Unable to load existing mixing form details. Please try again.",
      DETAILS_NOT_FOUND: "No saved mixing form data found for this submission.",
      FORM_ID_MISSING: "Unable to continue. Form ID is missing for this batch.",
      BATCH_ID_MISSING: "Unable to create form. Batch ID is missing.",
      SUB_DEPARTMENT_MISSING: "Unable to proceed. Sub-department context is missing.",
      EMPTY_FORM_ERROR: "Add at least one value before saving or submitting.",
      CREATE_FAILED: "Failed to create mixing form.",
      UPDATE_FAILED: "Failed to update mixing form.",
      CREATE_DRAFT_SUCCESS: "Mixing form saved as draft successfully.",
      CREATE_SUBMIT_SUCCESS: "Mixing form submitted for approval successfully.",
      UPDATE_DRAFT_SUCCESS: "Mixing form saved as draft successfully.",
      UPDATE_SUBMIT_SUCCESS: "Mixing form resubmitted for approval successfully.",
      UNSAVED_BACK_TITLE: "Unsaved changes detected",
      UNSAVED_BACK_MESSAGE: "You have unsaved mixing changes. Save as draft to avoid losing your data.",
      UNSAVED_BACK_CONFIRM: "Go back to Form",
      UNSAVED_BACK_DISCARD: "Discard Changes",
    },
    CASTING_CURING: {
      TITLE: "Casting and Curing",
      COL_STAGE: "Stage",
      COL_CC_STATUS: "CC Status",
      TABLE_LABEL: "Casting and curing batch list",
      EMPTY_TEXT: "No casting and curing batches found",
      NEW_LABEL: "New Submission",
      FORM_TITLE: "Casting and Curing",
      FORM_SUBTITLE: "Bowl details and curing operation parameters",
      SECTION_BOWL_TITLE: "Bowl Details",
      SECTION_BOWL_SUBTITLE: "Per-bowl propellant quantity, viscosity, arrival time and slurry cast data",
      SECTION_CASTING_TITLE: "Casting Details",
      SECTION_CASTING_SUBTITLE: "Vacuum build-up, casting progression, load cell readings and weight records",
      SECTION_CURING_TITLE: "Curing Details",
      SECTION_CURING_SUBTITLE: "Temperature achievement, curing cycle, soaking and hardness verification",
      ADD_BOWL_ROW: "Add Bowl Row",
      DETAILS_FETCH_ERROR: "Unable to load existing casting and curing form details. Please try again.",
      DETAILS_NOT_FOUND: "No saved casting and curing form data found for this submission.",
      FORM_ID_MISSING: "Unable to continue. Form ID is missing for this batch.",
      BATCH_ID_MISSING: "Unable to create form. Batch ID is missing.",
      SUB_DEPARTMENT_MISSING: "Unable to proceed. Sub-department context is missing.",
      EMPTY_FORM_ERROR: "Add at least one value before saving or submitting.",
      CREATE_FAILED: "Failed to create casting and curing form.",
      UPDATE_FAILED: "Failed to update casting and curing form.",
      CREATE_DRAFT_SUCCESS: "Casting and curing form saved as draft successfully.",
      CREATE_SUBMIT_SUCCESS: "Casting and curing form submitted for approval successfully.",
      UPDATE_DRAFT_SUCCESS: "Casting and curing form saved as draft successfully.",
      UPDATE_SUBMIT_SUCCESS: "Casting and curing form resubmitted for approval successfully.",
      UNSAVED_BACK_TITLE: "Unsaved changes detected",
      UNSAVED_BACK_MESSAGE: "You have unsaved casting and curing changes. Save as draft to avoid losing your data.",
      UNSAVED_BACK_CONFIRM: "Go back to Form",
      UNSAVED_BACK_DISCARD: "Discard Changes",
      SCHEMA_LOADING: "Loading schema…",
      FLOW_CASTING_TYPE: "Type of Casting",
      FLOW_CASTING_TYPE_PLACEHOLDER: "Select casting type",
      FLOW_CASTING_STATION: "Casting Station",
      FLOW_CASTING_STATION_PLACEHOLDER: "Select station",
      FLOW_MOTOR_COUNT: "Number of Motors",
      FLOW_MOTOR_COUNT_PLACEHOLDER: "Select count",
      FLOW_MOTOR_ID: "Motor ID",
      FLOW_MOTOR_ID_PLACEHOLDER: "Select motor",
      FLOW_MOTOR_RECEIVED_AT: "Motor Received Date & Time",
      FLOW_MOTOR_RECEIVED_AT_PLACEHOLDER: "DD-MM-YYYY HH:mm",
      FLOW_START_FORM: "Load Form",
      CASTING_SECTION_TITLE: "Casting",
      CURING_SECTION_TITLE: "Curing",
      MOTOR_CARD_TITLE: "Motor",
    },
    POST_CURE: {
      TITLE: "Post-Cure Operations",
      COL_OPERATION_TYPE: "Operation Type",
      COL_PC_STATUS: "PC Status",
      TABLE_LABEL: "Post-cure operation batch list",
      EMPTY_TEXT: "No post-cure operation batches found",
      NEW_LABEL: "New Submission",
      FORM_TITLE: "Post-Cure Operations",
      FORM_SUBTITLE: "De-coring, trimming, LF filling and inhibition resin application",
      SECTION_TITLE: "Post-Cure Operations",
      SECTION_SUBTITLE: "Record de-coring, trimming, LF filling and IR application for each motor",
      DETAILS_FETCH_ERROR: "Unable to load existing post-cure form details. Please try again.",
      DETAILS_NOT_FOUND: "No saved post-cure form data found for this submission.",
      FORM_ID_MISSING: "Unable to continue. Form ID is missing for this batch.",
      BATCH_ID_MISSING: "Unable to create form. Batch ID is missing.",
      SUB_DEPARTMENT_MISSING: "Unable to proceed. Sub-department context is missing.",
      EMPTY_FORM_ERROR: "Add at least one value before saving or submitting.",
      CREATE_FAILED: "Failed to create post-cure form.",
      UPDATE_FAILED: "Failed to update post-cure form.",
      CREATE_DRAFT_SUCCESS: "Post-cure form saved as draft successfully.",
      CREATE_SUBMIT_SUCCESS: "Post-cure form submitted for approval successfully.",
      UPDATE_DRAFT_SUCCESS: "Post-cure form saved as draft successfully.",
      UPDATE_SUBMIT_SUCCESS: "Post-cure form resubmitted for approval successfully.",
      UNSAVED_BACK_TITLE: "Unsaved changes detected",
      UNSAVED_BACK_MESSAGE: "You have unsaved post-cure changes. Save as draft to avoid losing your data.",
      UNSAVED_BACK_CONFIRM: "Go back to Form",
      UNSAVED_BACK_DISCARD: "Discard Changes",
    },
  },
  QUALITY_CONTROL: {
    DEPARTMENT_NAME: "Quality Control Department",
    BATCH_LIST: {
      COL_BATCH_ID: "Batch ID",
      COL_MOTOR_ID: "Motor ID",
      COL_TYPE: "Type",
      COL_MANAGER: "Manager",
      COL_CREATED_ON: "Created On",
      COL_PRIORITY: "Priority",
      MOTOR_TYPE_PREFIX: "Type ",
      UNASSIGNED: "Unassigned",
      FILL_ACTION: "Fill Specifications",
      CONTINUE_ACTION: "Continue Filling",
      EDIT_ACTION_TOOLTIP: "Load previously submitted data for editing",
    },
    FORM_HEADER: {
      BACK_TO_LIST: "Back to List",
      EDITING_REJECTED: "Editing Rejected Submission",
      REJECTION_REASON: "Rejection Reason",
    },
    RAW_MATERIAL_REVALIDATION: {
      NEW_LABEL: "New Revalidation",
      TABLE_LABEL: "QC raw material revalidation batch list",
      COL_STATUS: "QC Status",
      DETAILS_FETCH_ERROR: "Unable to load existing revalidation form details. Please try again.",
      DETAILS_NOT_FOUND: "No saved revalidation form data found for this submission.",
      FORM_ID_MISSING: "Unable to continue. Form ID is missing for this batch.",
      BATCH_ID_MISSING: "Unable to create form. Batch ID is missing.",
      SUB_DEPARTMENT_MISSING: "Unable to proceed. Sub-department context is missing.",
      TITLE: "Raw Material Revalidation",
      SUBTITLE: "Add ingredients, record test results and validity status",
      EDIT_MODE_BANNER: "You are editing a rejected submission. Previously submitted values are pre-loaded. Review and correct before resubmitting.",
      SELECT_INGREDIENT_LABEL: "Select Ingredient",
      SELECT_INGREDIENT_PLACEHOLDER: "Choose ingredient",
      ADD_TO_FORM: "Add to Form",
      BLOCK_LABEL: "Block",
      PARAMETER_LABEL: "Parameter",
      PARAMETERS_SUFFIX: "params",
      NO_INGREDIENTS_TITLE: "No ingredient added yet",
      NO_INGREDIENTS_SUBTITLE: "Select an ingredient above and click \"Add to Form\" to begin",
      INFO_NOTE: "Fill all results and set validity status before submitting. You can save as draft and continue later.",
      REMOVE_BLOCK_TOOLTIP: "Remove this block",
      LOT_PLACEHOLDER: "e.g. LOT-2024-01",
      RESULT_PLACEHOLDER: "Enter value",
      VALIDITY_PLACEHOLDER: "Enter validity",
      RESULTS_FILLED_SUFFIX: "Results Filled",
      BLOCK_SUFFIX: "Block",
      BLOCK_SUFFIX_PLURAL: "Blocks",
      SAVE_DRAFT_LABEL: "Save as Draft",
      SUBMIT_LABEL: "Submit for Approval",
      RESUBMIT_LABEL: "Resubmit for Approval",
      READY_TO_SUBMIT: "Ready to submit for approval",
      NOT_READY_TO_SUBMIT: "Add at least one ingredient and fill in some results to submit",
      EMPTY_STATE_ACTION: "No ingredients added yet",
      EMPTY_STATE_PROGRESS: "ingredient",
      DRAFT_CONFIRM_TITLE: "Save as Draft?",
      DRAFT_CONFIRM_MESSAGE: "Your progress will be saved. You can return and continue filling the form later. The batch status will be marked as 'In Progress'.",
      DRAFT_CONFIRM_LABEL: "Save Draft",
      SUBMIT_CONFIRM_TITLE: "Submit for Approval?",
      RESUBMIT_CONFIRM_TITLE: "Resubmit for Approval?",
      SUBMIT_CONFIRM_MESSAGE: "Once submitted, you will not be able to edit this form until the approver takes action. Make sure all data is accurate.",
      RESUBMIT_CONFIRM_MESSAGE: "You are resubmitting a previously rejected entry. Ensure all corrections have been made before sending for review.",
      SUBMIT_CONFIRM_LABEL: "Submit",
      RESUBMIT_CONFIRM_LABEL: "Resubmit",
      CONFIRM_CANCEL_LABEL: "Cancel",
      CONFIRM_GO_BACK_LABEL: "Go Back",
      EMPTY_FORM_ERROR: "Add at least one ingredient result before saving or submitting.",
      CREATE_FAILED: "Failed to create raw material revalidation form.",
      UPDATE_FAILED: "Failed to update raw material revalidation form.",
      CREATE_DRAFT_SUCCESS: "Revalidation draft saved successfully.",
      UPDATE_DRAFT_SUCCESS: "Revalidation draft updated successfully.",
      CREATE_SUBMIT_SUCCESS: "Revalidation submitted for approval successfully.",
      UPDATE_SUBMIT_SUCCESS: "Revalidation resubmitted for approval successfully.",
      UNSAVED_BACK_TITLE: "Unsaved changes detected",
      UNSAVED_BACK_MESSAGE: "You have unsaved revalidation changes. Save as draft to avoid losing your data.",
      UNSAVED_BACK_CONFIRM: "Go back to Form",
      UNSAVED_BACK_DISCARD: "Discard Changes",
    },
    QC_DIVISION: {
      NEW_LABEL: "New Submission",
      TABLE_LABEL: "QC division batch list",
      COL_STATUS: "QC Status",
      TITLE: "QC Division - In Process Checks",
      SUBTITLE: "Record actual values for each operation stage",
      EDIT_MODE_BANNER: "You are editing a rejected submission. Previously submitted values are pre-loaded. Review and correct before resubmitting.",
      DETAILS_FETCH_ERROR: "Unable to load existing in-process check details. Please try again.",
      DETAILS_NOT_FOUND: "No saved in-process check data found for this submission.",
      FORM_ID_MISSING: "Unable to continue. Form ID is missing for this batch.",
      BATCH_ID_MISSING: "Unable to create form. Batch ID is missing.",
      SUB_DEPARTMENT_MISSING: "Unable to proceed. Sub-department context is missing.",
      CREATE_FAILED: "Failed to create in-process checks form.",
      UPDATE_FAILED: "Failed to update in-process checks form.",
      READY_TO_SUBMIT: "Ready to submit for approval",
      NOT_READY_TO_SUBMIT: "Fill at least one field to submit",
      SAVE_DRAFT_LABEL: "Save as Draft",
      SUBMIT_LABEL: "Submit for Approval",
      RESUBMIT_LABEL: "Resubmit for Approval",
      DRAFT_CONFIRM_TITLE: "Save as Draft?",
      DRAFT_CONFIRM_MESSAGE: "Your progress will be saved. You can return and continue filling the form later.",
      DRAFT_CONFIRM_LABEL: "Save Draft",
      SUBMIT_CONFIRM_TITLE: "Submit for Approval?",
      RESUBMIT_CONFIRM_TITLE: "Resubmit for Approval?",
      SUBMIT_CONFIRM_MESSAGE: "Once submitted, you will not be able to edit this form until the approver takes action.",
      RESUBMIT_CONFIRM_MESSAGE: "You are resubmitting a previously rejected entry. Ensure all corrections have been made.",
      SUBMIT_CONFIRM_LABEL: "Submit",
      RESUBMIT_CONFIRM_LABEL: "Resubmit",
      CONFIRM_CANCEL_LABEL: "Cancel",
      CONFIRM_GO_BACK_LABEL: "Go Back",
      UNSAVED_BACK_TITLE: "Unsaved changes detected",
      UNSAVED_BACK_MESSAGE: "You have unsaved QC division changes. Save as draft to avoid losing your data.",
      UNSAVED_BACK_CONFIRM: "Go back to Form",
      UNSAVED_BACK_DISCARD: "Discard Changes",
      EMPTY_FORM_ERROR: "Add at least one in-process value before saving or submitting.",
      CREATE_DRAFT_SUCCESS: "QC division draft saved successfully.",
      UPDATE_DRAFT_SUCCESS: "QC division draft updated successfully.",
      CREATE_SUBMIT_SUCCESS: "QC division record submitted for approval successfully.",
      UPDATE_SUBMIT_SUCCESS: "QC division record resubmitted for approval successfully.",
    },
    NDT: {
      NEW_LABEL: "New NDT Submission",
      TABLE_LABEL: "NDT batch list",
      COL_STATUS: "NDT Status",
      TITLE: "NDT",
      SUBTITLE: "Non-destructive testing - defect observations",
      EDIT_MODE_BANNER: "You are editing a rejected submission. Previously submitted values are pre-loaded. Review and correct before resubmitting.",
      DETAILS_FETCH_ERROR: "Unable to load existing NDT report details. Please try again.",
      DETAILS_NOT_FOUND: "No saved NDT report data found for this submission.",
      FORM_ID_MISSING: "Unable to continue. Form ID is missing for this batch.",
      BATCH_ID_MISSING: "Unable to create form. Batch ID is missing.",
      SUB_DEPARTMENT_MISSING: "Unable to proceed. Sub-department context is missing.",
      CREATE_FAILED: "Failed to create NDT report.",
      UPDATE_FAILED: "Failed to update NDT report.",
      READY_TO_SUBMIT: "Data entered - ready to submit",
      NOT_READY_TO_SUBMIT: "Fill at least one observation or test value",
      EDIT_MODE_HELP: "Resubmit after correcting flagged values",
      NORMAL_MODE_HELP: "You can save a draft and return later",
      SAVE_DRAFT_LABEL: "Save as Draft",
      SUBMIT_LABEL: "Submit for Approval",
      RESUBMIT_LABEL: "Resubmit for Approval",
      DRAFT_CONFIRM_TITLE: "Save as Draft?",
      DRAFT_CONFIRM_MESSAGE: "Progress saved. You can return and continue filling later.",
      DRAFT_CONFIRM_LABEL: "Save Draft",
      SUBMIT_CONFIRM_TITLE: "Submit for Approval?",
      RESUBMIT_CONFIRM_TITLE: "Resubmit for Approval?",
      SUBMIT_CONFIRM_MESSAGE: "Once submitted, editing is locked until the approver acts.",
      RESUBMIT_CONFIRM_MESSAGE: "Ensure all corrections have been made before resubmitting.",
      SUBMIT_CONFIRM_LABEL: "Submit",
      RESUBMIT_CONFIRM_LABEL: "Resubmit",
      CONFIRM_CANCEL_LABEL: "Cancel",
      CONFIRM_GO_BACK_LABEL: "Go Back",
      UNSAVED_BACK_TITLE: "Unsaved changes detected",
      UNSAVED_BACK_MESSAGE: "You have unsaved NDT changes. Save as draft to avoid losing your data.",
      UNSAVED_BACK_CONFIRM: "Go back to Form",
      UNSAVED_BACK_DISCARD: "Discard Changes",
      EMPTY_FORM_ERROR: "Add at least one NDT observation or result before saving or submitting.",
      CREATE_DRAFT_SUCCESS: "NDT draft saved successfully.",
      UPDATE_DRAFT_SUCCESS: "NDT draft updated successfully.",
      CREATE_SUBMIT_SUCCESS: "NDT report submitted for approval successfully.",
      UPDATE_SUBMIT_SUCCESS: "NDT report resubmitted for approval successfully.",
    },
    STATIC_TEST_FACILITY: {
      NEW_LABEL: "New STF Record",
      TABLE_LABEL: "Static Test Facility batch list",
      COL_STATUS: "STF Status",
      TITLE: "Static Test Facility - Weight Log",
      SUBTITLE: "Record STF weight values and auto-calculate propellant weight",
      EDIT_MODE_BANNER: "You are editing a rejected submission. Previously submitted values are pre-loaded. Review and correct before resubmitting.",
      DETAILS_FETCH_ERROR: "Unable to load existing STF details. Please try again.",
      DETAILS_NOT_FOUND: "No saved STF data found for this submission.",
      FORM_ID_MISSING: "Unable to continue. Form ID is missing for this batch.",
      BATCH_ID_MISSING: "Unable to create form. Batch ID is missing.",
      SUB_DEPARTMENT_MISSING: "Unable to proceed. Sub-department context is missing.",
      CREATE_FAILED: "Failed to create STF record.",
      UPDATE_FAILED: "Failed to update STF record.",
      READY_TO_SUBMIT: "Ready to submit for approval",
      NOT_READY_TO_SUBMIT: "Fill at least one field to submit",
      SAVE_DRAFT_LABEL: "Save as Draft",
      SUBMIT_LABEL: "Submit for Approval",
      RESUBMIT_LABEL: "Resubmit for Approval",
      DRAFT_CONFIRM_TITLE: "Save as Draft?",
      DRAFT_CONFIRM_MESSAGE: "Your progress will be saved. You can return and continue later.",
      DRAFT_CONFIRM_LABEL: "Save Draft",
      SUBMIT_CONFIRM_TITLE: "Submit for Approval?",
      RESUBMIT_CONFIRM_TITLE: "Resubmit for Approval?",
      SUBMIT_CONFIRM_MESSAGE: "Once submitted, editing is locked until the approver acts.",
      RESUBMIT_CONFIRM_MESSAGE: "Ensure all corrections have been made before resubmitting.",
      SUBMIT_CONFIRM_LABEL: "Submit",
      RESUBMIT_CONFIRM_LABEL: "Resubmit",
      CONFIRM_CANCEL_LABEL: "Cancel",
      CONFIRM_GO_BACK_LABEL: "Go Back",
      UNSAVED_BACK_TITLE: "Unsaved changes detected",
      UNSAVED_BACK_MESSAGE: "You have unsaved STF changes. Save as draft to avoid losing your data.",
      UNSAVED_BACK_CONFIRM: "Go back to Form",
      UNSAVED_BACK_DISCARD: "Discard Changes",
      EMPTY_FORM_ERROR: "Add at least one STF value before saving or submitting.",
      CREATE_DRAFT_SUCCESS: "STF draft saved successfully.",
      UPDATE_DRAFT_SUCCESS: "STF draft updated successfully.",
      CREATE_SUBMIT_SUCCESS: "STF record submitted for approval successfully.",
      UPDATE_SUBMIT_SUCCESS: "STF record resubmitted for approval successfully.",
    },
  },
  DISPATCH: {
    NEW_LABEL: "New Dispatch Record",
    TABLE_LABEL: "Dispatch batch list",
    COL_STATUS: "Dispatch Status",
    EDIT_ACTION: "Edit & Resubmit",
    WAITING_LABEL: "Awaiting Approver",
    APPROVED_LABEL: "Approved",
    TITLE: "Dispatch - Details Log",
    FIELD_CASTING_DATE: "Casting Date",
    FIELD_FINAL_WEIGHT: "Final Weight",
    FIELD_WAIVERS: "Waivers if any",
    FIELD_NDT_MOM: "NDT Committee Clearance MOM Number",
    FIELD_FINAL_ACCEPTANCE_MOM: "Final Acceptance Clearance MOM Number",
    FIELD_DEVIATION: "Deviation Details",
    FIELD_DISPATCH_DATE: "Dispatch Date",
    FIELD_DISPATCH_LOCATION: "Dispatch Location",
    SUPPORTING_FILES_TITLE: "Supporting Files",
    SUPPORTING_FILES_SUBTITLE: "Upload documents, certificates, or any supporting attachments",
    UPLOAD_FILES: "Upload Files",
    FILE_PLACEHOLDER_TITLE: "Click to browse or drag and drop files here",
    FILE_PLACEHOLDER_SUBTITLE: "Supported: PDF, DOC, DOCX, XLS, XLSX, JPG, PNG, ZIP",
    ADD_MORE_FILES: "Add more files",
    REMOVE_FILE_TOOLTIP: "Remove file",
    READY_TO_SUBMIT: "Ready to submit for approval",
    NOT_READY_TO_SUBMIT: "Fill at least one field or attach one file to submit",
    SAVE_DRAFT_LABEL: "Save as Draft",
    SUBMIT_LABEL: "Submit for Approval",
    RESUBMIT_LABEL: "Resubmit for Approval",
    SUBMIT_DISABLED_TOOLTIP: "Fill at least one field or attach one file before submitting",
    DRAFT_CONFIRM_TITLE: "Save as Draft?",
    DRAFT_CONFIRM_MESSAGE: "Your progress will be saved. You can return and continue later.",
    DRAFT_CONFIRM_LABEL: "Save Draft",
    SUBMIT_CONFIRM_TITLE: "Submit for Approval?",
    RESUBMIT_CONFIRM_TITLE: "Resubmit for Approval?",
    SUBMIT_CONFIRM_MESSAGE: "Once submitted, editing is locked until the approver acts.",
    RESUBMIT_CONFIRM_MESSAGE: "Ensure all corrections have been made before resubmitting.",
    SUBMIT_CONFIRM_LABEL: "Submit",
    RESUBMIT_CONFIRM_LABEL: "Resubmit",
    CONFIRM_CANCEL_LABEL: "Cancel",
    CONFIRM_GO_BACK_LABEL: "Go Back",
    EDIT_MODE_BANNER: "You are editing a rejected submission. Previously submitted values are pre-loaded. Review and correct before resubmitting.",
    DETAILS_FETCH_ERROR: "Unable to load existing dispatch details. Please try again.",
    DETAILS_NOT_FOUND: "No saved dispatch data found for this submission.",
    FORM_ID_MISSING: "Unable to continue. Form ID is missing for this batch.",
    BATCH_ID_MISSING: "Unable to create form. Batch ID is missing.",
    SUB_DEPARTMENT_MISSING: "Unable to proceed. Sub-department context is missing.",
    EMPTY_FORM_ERROR: "Add at least one dispatch value before saving or submitting.",
    CREATE_FAILED: "Failed to create dispatch record.",
    UPDATE_FAILED: "Failed to update dispatch record.",
    CREATE_DRAFT_SUCCESS: "Dispatch draft saved successfully.",
    UPDATE_DRAFT_SUCCESS: "Dispatch draft updated successfully.",
    CREATE_SUBMIT_SUCCESS: "Dispatch record submitted for approval successfully.",
    UPDATE_SUBMIT_SUCCESS: "Dispatch record resubmitted for approval successfully.",
    UNSAVED_BACK_TITLE: "Unsaved changes detected",
    UNSAVED_BACK_MESSAGE: "You have unsaved dispatch changes. Save as draft to avoid losing your data.",
    UNSAVED_BACK_CONFIRM: "Go back to Form",
    UNSAVED_BACK_DISCARD: "Discard Changes",
  },
  APPROVER: {
    COMMON: {
      ROLE: "Approver",
      OVERVIEW: "Overview",
      VIEW: "View",
      VIEW_DETAILS: "View Details",
      VIEW_PDF: "View as PDF",
      APPROVE: "Approve",
      REJECT: "Reject",
      STATUS_ALL: "All",
      STATUS_PENDING: "Pending",
      STATUS_APPROVED: "Approved",
      STATUS_REJECTED: "Rejected",
      UNKNOWN_SUB_DEPARTMENT: (subDepartment = "") => `Unknown sub-department: ${subDepartment}`,
      VALID_ROUTES: (routes: string[]) => `Valid routes: ${routes.join(" · ")}`,
    },
    LIST: {
      SEARCH_PLACEHOLDER: (fields: string[]) =>
        fields.length > 0 ? `Search ${fields.join(", ")}...` : "Search records...",
      RESULTS: (count: number) => `${count} result${count === 1 ? "" : "s"}`,
      EMPTY_TITLE: "No submissions match your filters",
      EMPTY_SUBTITLE: "Try adjusting the search or status filter",
    },
    ACTION: {
      APPROVE_TITLE: "Approve Submission?",
      REJECT_TITLE: "Reject Submission?",
      APPROVE_MESSAGE: "This submission will be marked as approved and moved out of the approver queue.",
      REJECT_MESSAGE: "This submission will be marked as rejected and sent back for correction.",
      APPROVE_LABEL: "Approve",
      REJECT_LABEL: "Reject",
      CANCEL_LABEL: "Cancel",
      REMARKS_LABEL: "Remarks",
      REMARKS_PLACEHOLDER: "Add optional approval remarks",
      REJECTION_REASON_LABEL: "Rejection Reason",
      REJECTION_REASON_PLACEHOLDER: "Explain why this submission is being rejected",
      REJECTION_REASON_REQUIRED: "Rejection reason is required.",
      BATCH_ID_LABEL: "Batch ID",
      LOT_ID_LABEL: "Lot ID",
      MOTOR_CASING_ID_LABEL: "Motor casing ID",
      FORM_ID_MISSING: "Unable to process this request because the form ID is missing.",
      SUBDEPARTMENT_MISSING: "Unable to process this request because the approver sub-department could not be resolved.",
      INVALID_STATUS: "This submission cannot be actioned in its current state.",
      APPROVING: "Approving submission...",
      REJECTING: "Rejecting submission...",
      FAILED: "Failed to update submission status.",
    },
    PDF: {
      TITLE: "PDF Preview",
      INLINE_LOADING: "Loading PDF preview...",
      DOWNLOAD_LOADING: "Preparing PDF download...",
      DOWNLOAD_LABEL: "Download PDF",
      EMPTY_TITLE: "PDF preview unavailable",
      EMPTY_SUBTITLE: "Try again after the form data has been loaded.",
      FORM_ID_MISSING: "Unable to generate the PDF because the form ID is missing.",
      SUBDEPARTMENT_MISSING: "Unable to generate the PDF because the approver sub-department could not be resolved.",
      FAILED: "Failed to generate PDF.",
    },
    DASHBOARD: {
      KPI: {
        TOTAL_PENDING: "Total Pending",
        TOTAL_APPROVED: "Total Approved",
        TOTAL_REJECTED: "Total Rejected",
        TOTAL_QUEUES: "Sub-departments",
      },
      PENDING_BADGE: (count: number) => `${count} pending`,
      SECTION_TITLE: "Sub-Department Queues",
      SOURCING: {
        DEPARTMENT_NAME: "Sourcing Department",
        RAW_MATERIAL_LABEL: "Raw Material Procurement",
        RAW_MATERIAL_DESCRIPTION:
          "Procurement approvals, material traceability and vendor clearance records",
        RAW_MATERIAL_SECTION: "Raw Material Submissions",
        ROCKET_CASING_LABEL: "Rocket Motor Casing",
        ROCKET_CASING_DESCRIPTION:
          "Motor casing verification, dimensional validation and release approvals",
        ROCKET_CASING_SECTION: "Rocket Casing Submissions",
      },
      MANUFACTURING: {
        DEPARTMENT_NAME: "Manufacturing Department",
        RAW_MATERIAL_LABEL: "Raw Material Preparation",
        RAW_MATERIAL_DESCRIPTION:
          "HTPB weighing, DOA mixing, curing agent and binder preparation approvals",
        RAW_MATERIAL_SECTION: "Raw Material Preparation Submissions",
        CASE_PREP_LABEL: "Case Preparation",
        CASE_PREP_DESCRIPTION:
          "Motor case lining, mandrel assembly and dimensional approval checks",
        CASE_PREP_SECTION: "Case Preparation Submissions",
        MIXING_LABEL: "Mixing",
        MIXING_DESCRIPTION:
          "Propellant slurry mixing, viscosity review and cure-rate QC approvals",
        MIXING_SECTION: "Mixing Submissions",
        CASTING_LABEL: "Casting & Curing",
        CASTING_DESCRIPTION:
          "Casting into motor cases, cure-cycle monitoring and release decisions",
        CASTING_SECTION: "Casting & Curing Submissions",
        POST_CURE_LABEL: "Post-Cure Operations",
        POST_CURE_DESCRIPTION:
          "X-ray inspection, dimensional verification and post-cure disposition approvals",
        POST_CURE_SECTION: "Post-Cure Operations Submissions",
      },
      DISPATCH: {
        DEPARTMENT_NAME: "Dispatch Department",
        LABEL: "Dispatch",
        DESCRIPTION:
          "Motor dispatch clearance, transport documentation and consignment approvals",
        SECTION: "Dispatch Submissions",
      },
      QUALITY_CONTROL: {
        DEPARTMENT_NAME: "Quality Control Department",
        RAW_MATERIAL_LABEL: "Raw Material Revalidation",
        RAW_MATERIAL_DESCRIPTION:
          "HTPB, DOA, AP, Al and binder revalidation test result approvals",
        RAW_MATERIAL_SECTION: "Raw Material Revalidation Submissions",
        QC_DIVISION_LABEL: "QC Division",
        QC_DIVISION_DESCRIPTION:
          "In-process quality checks and dimensional inspection record approvals",
        QC_DIVISION_SECTION: "QC Division Submissions",
        NDT_LABEL: "NDT",
        NDT_DESCRIPTION:
          "X-ray, ultrasonic and dye-penetrant inspection report approvals",
        NDT_SECTION: "NDT Submissions",
        STF_LABEL: "Static Test Facility",
        STF_DESCRIPTION:
          "Ballistic test data, burn rate and performance verification approvals",
        STF_SECTION: "Static Test Facility Submissions",
      },
    },
  },
    /* -------- DEPARTMENT HEADER CARD -------- */
  DEPARTMENT_HEADER: {
    // Fallback / placeholder values
    DEFAULT_DEPT:     "Department",
    DEFAULT_SUB_DEPT: "Sub Department",
    DEFAULT_USER:     "User",
    DEFAULT_ROLE:     "Role",

    // Chip labels
    LABEL_USER: "User",
    LABEL_ROLE: "Role",

    // Stat tile labels
    STAT_ALLOCATED: "Allocated",
    STAT_COMPLETED: "Completed & Submitted",
    STAT_DRAFT:     "Draft Saved",
    STAT_PENDING:   "Pending",
  },

  /* -------- DASHBOARD PAGE -------- */
  DASHBOARD_PAGE: {
    HEADER: {
      EYEBROW: "System Supervisor Console",
      TITLE: "Admin Dashboard",
    },

    // ── KPI ──────────────────────────────────────────────────────
    KPI: {
      ACTIVE_USERS:       "Active Users",
      OPEN_BATCHES:       "Open Batches",
      MOTORS_DISPATCHED:  "Motors Dispatched",
      PENDING_APPROVALS:  "Pending Approvals",

      SUB_USERS:     "+12% than last week",
      SUB_BATCHES:   "+3 new this month",
      SUB_DISPATCH:  "+8% than last quarter",
      SUB_APPROVALS: "Requires attention",
    },

    // ── Charts ───────────────────────────────────────────────────
    CHARTS: {
      BATCH_ACTIVITY: {
        TITLE:    "Weekly Batch Activity",
        SUBTITLE: "Batches initiated across all stages",
      },
      MOTORS_PROCESSED: {
        TITLE:    "Motors Processed",
        SUBTITLE: "Motors Processed from last quarter.",
      },
      QC_PASS_RATE: {
        TITLE:    "QC Pass Rate (%)",
        SUBTITLE: "Quality checks across all processing stages",
      },
    },

    // ── Active Batches Table ─────────────────────────────────────
    BATCH_TABLE: {
      SECTION_TITLE:     "In Progress Batches",
      COLUMN_HEADERS: ["Batch ID", "Type", "Motor ID", "Motor Type", "Project Name", "Manager Name", "Manager ID", "Status", "Created Date", "Progress"],
      HEADERS: {
        BATCH_ID: "BATCH ID",
        BATCH_TYPE: "BATCH TYPE",
        MOTOR_ID:    "MOTOR ID",
        MOTOR_TYPE:  "MOTOR TYPE",
        PROJECT_NAME: "PROJECT NAME",
        MANAGER_NAME: "MANAGER NAME",
        SYSTEM_MANAGER_ID:   "MANAGER ID",
        STATUS:      "STATUS",
        CREATED_DATE: "CREATED DATE",
        PROGRESS:    "PROGRESS",
      },
    },

    // ── Blockchain Events Timeline ───────────────────────────────
    BLOCKCHAIN_EVENTS: {
      SECTION_TITLE:     "Blockchain Events",
    },

    // ── Date Filter ──────────────────────────────────────────────
    DATE_FILTER: {
      LABEL:      "Date Filter",
      TODAY:      "Today",
      THIS_WEEK:  "This Week",
      THIS_MONTH: "This Month",
      CUSTOM:     "Custom Range",
      START_DATE: "Start Date",
      END_DATE:   "End Date",
      VALUES: { DAY: "day", WEEK: "week", MONTH: "month", CUSTOM: "custom" },
    },

    // ── Filter UI Labels & Buttons ────────────────────────────────
    FILTERS: {
      BUTTON:          "Filters",
      TIMELINE_LABEL:  "Timeline Filters",
      STAGE:           "Stage",
      TYPE:            "Type",
      STATUS:          "Status",
      DEPARTMENT:      "Dept",
      FROM:            "From",
      TO:              "To",
      THIS_MONTH_CHIP: "This month",
      DATE_SEPARATOR:  "\u2014",
      CLEAR_ALL:       "Clear all",
    },

    // ── Search Placeholders ───────────────────────────────────────
    PLACEHOLDERS: {
      BATCH_SEARCH: "Search batch, motor, project\u2026",
      EVENT_SEARCH: "Search events...",
    },

    // ── Empty States ─────────────────────────────────────────────
    EMPTY_STATES: {
      NO_BATCHES: "No batches match the selected filters.",
      NO_EVENTS:  "No events match the selected filters.",
    },

    // ── Batch Filter Options ──────────────────────────────────────
    BATCH_FILTERS: {
      STAGES:   ["All", "Manufacturing", "Quality Control", "Sourcing", "Dispatch"],
      TYPES:    ["All", "MainScale", "SubScale"],
      STATUSES: ["All", "Active", "Inactive"],
    },

    // ── Event Filter Options ──────────────────────────────────────
    EVENT_FILTERS: {
      TYPES:       ["All", "STAGE_UPDATED", "APPROVAL_COMPLETED", "QC_PASSED", "DISPATCHED"],
      DEPARTMENTS: ["All", "Manufacturing", "Quality Control", "Sourcing", "Dispatch"],
    },
  },

  /* -------- ADMIN USER MANAGEMENT -------- */
  USER_MANAGEMENT: {
    PAGE: {
      TITLE: "User Management",
      SUBTITLE: "Manage user accounts, roles and department access",
      NEW_USER_BUTTON: "New User",
      LOADING_PLACEHOLDER: "…",
    },
    STATS: [
      { label: "Total Users",       subLabel: "Registered accounts",    variant: "total" },
      { label: "Active",            subLabel: "Currently enabled",      variant: "active" },
      { label: "Inactive",          subLabel: "Access suspended",       variant: "inactive" },
      { label: "Actions Required",  subLabel: "Pending reset requests", variant: "reset" },
    ],
    TOOLBAR: {
      SEARCH_PLACEHOLDER: "Search by name or username…",
      FILTERS_BUTTON: "Filters",
      FILTERS_BUTTON_WITH_COUNT: (n: number) => `Filters (${n})`,
      CLEAR_ALL: "Clear all",
      FILTER_ROLE_LABEL: "Role",
      FILTER_DEPT_LABEL: "Department",
      FILTER_STATUS_LABEL: "Status",
    },
    STATUSES: ["Active", "Inactive"],
    MESSAGES: {
      LOAD_USER_FAILED: "Failed to load user details.",
      SAVE_SUCCESS: "Saved successfully.",
      OPERATION_FAILED: "Operation failed.",
      DELETE_SUCCESS: "User deleted successfully.",
      DELETE_FAILED: "Failed to delete user.",
      SAVING_USER: "Saving user data...",
      DELETING_USER: "Deleting user...",
    },
    ERRORS: {
      LOAD_LIST_FAILED: "Failed to load user list:",
      LOAD_STATS_FAILED: "Failed to load user stats",
      LOAD_LOOKUPS_FAILED: "Failed to load user management lookups",
    }
  },

  /* -------- ADMIN BATCH MANAGEMENT -------- */
  BATCH_MANAGEMENT: {
    PAGE: {
      TITLE: "Batch Management",
      SUBTITLE: "Track and manage production batches across all stages",
      NEW_BATCH_BUTTON: "New Batch",
      LOADING_PLACEHOLDER: "…",
      REFRESH_TOOLTIP: "Refresh Data",
    },
    STATS: [
      { label: "Total Batches",  subLabel: "All registered batches",    variant: "total" },
      { label: "In Progress",    subLabel: "Currently active",          variant: "inProgress" },
      { label: "Completed",      subLabel: "Fully processed",           variant: "completed" },
      { label: "Pending",        subLabel: "Awaiting action",           variant: "pending" },
      { label: "Rejected",       subLabel: "Requires attention",        variant: "rejected" },
    ],
    TOOLBAR: {
      SEARCH_PLACEHOLDER: "Search batches…",
      FILTERS_BUTTON: "Filters",
      FILTERS_BUTTON_WITH_COUNT: (n: number) => `Filters (${n})`,
      CLEAR_ALL: "Clear all",
      FILTER_STAGE_LABEL: "Stage",
      FILTER_STATUS_LABEL: "Status",
      FILTER_PRIORITY_LABEL: "Priority",
      FILTER_DEPT_LABEL: "Department",
      TIMEFRAME_LABEL: "Timeframe",
      TODAY: "Today",
      THIS_WEEK: "This Week",
      THIS_MONTH: "This Month",
    },
    FILTER_OPTIONS: {
      STAGES:     ["All", "Sourcing", "Manufacturing", "Quality Control", "Dispatch"],
      STATUSES:   ["All", "Pending", "In Progress", "Completed", "Approved", "Dispatched", "Rejected"],
      PRIORITIES: ["All", "Low", "Medium", "High", "Critical"],
    },
    TABLE_COLS: ["Batch ID", "Motor ID", "Motor Stage", "Stage", "Status", "Priority", "System Manager", "Actions"],
    TABLE_ACTIONS: {
      COMPLETE_IMPLEMENTATION: "Complete Implementation Sheet",
      COMPLETE_IMPLEMENTATION_TOOLTIP: "Fill identification sheet and material details",
      VIEW_DETAILS: "View Details",
      VIEW_DETAILS_TOOLTIP: "View completed implementation sheet",
      EDIT_BATCH: "Edit batch",
      DELETE_BATCH: "Delete batch",
    },
    FORM: {
      IDENTIFICATION_LABEL: "Identification",
      PROJECT_LABEL:        "Project",
      PRIORITY_ASSIGNMENT_LABEL: "Priority & Assignment",
      BATCH_ID_LABEL:       "Batch ID",
      BATCH_ID_PLACEHOLDER: "e.g. BATCH-2024-001",
      MOTOR_ID_LABEL:       "Motor ID",
      MOTOR_ID_PLACEHOLDER: "e.g. RM-ACEM-2024-042",
      PROJECT_NAME_LABEL:   "Project Name",
      PROJECT_NAME_PLACEHOLDER: "e.g. ACEM Phase-II",
      BATCH_TYPE_LABEL:     "Batch Type",
      MOTOR_TYPE_LABEL:     "Motor Type",
      PRIORITY_LABEL:       "Priority",
      ASSIGNED_TO_LABEL:    "Assign System Manager",
      UNASSIGNED:           "Unassigned",
      EDIT_TITLE:           "Edit Batch",
      CREATE_TITLE:         "Create New Batch",
      EDIT_SUBTITLE:        (batchId: string) => `Editing batch ${batchId}`,
      CREATE_SUBTITLE:      "Fill in the batch details below.",
      CANCEL:               "Cancel",
      SAVE_CHANGES:         "Save Changes",
      CREATE_BATCH:         "Create Batch",
      SAVING:               "Saving…",
      BATCH_TYPES:          ["Subscale", "Main Batch"],
      MOTOR_TYPES:          ["A", "B", "C", "D"],
      PRIORITIES:           ["Low", "Medium", "High", "Critical"],
    },
    DELETE_DIALOG: {
      TITLE:              "Delete Batch?",
      BODY:               (batchId: string, motorId: string) =>
        `This will permanently remove batch ${batchId} (Motor: ${motorId}) and all associated processing data. This action cannot be undone.`,
      REASON_LABEL:       "Reason for deletion",
      REASON_PLACEHOLDER: "e.g. Duplicate entry, Test record, Data error…",
      REASON_HELPER:      "Reason is mandatory before deletion can proceed.",
      CANCEL:             "Cancel",
      CONFIRM:            "Delete Batch",
      DELETING:           "Deleting…",
    },
    MESSAGES: {
      SAVING_BATCH:     "Saving batch data...",
      DELETING_BATCH:   "Deleting batch...",
      SAVE_SUCCESS:     "Batch saved successfully.",
      OPERATION_FAILED: "Operation failed. Please try again.",
      DELETE_SUCCESS:   "Batch deleted successfully.",
      DELETE_FAILED:    "Failed to delete batch.",
      LOAD_BATCH_FAILED:"Failed to load batch details.",
    },
    ERRORS: {
      LOAD_LIST_FAILED:  "Failed to load batch list.",
      LOAD_STATS_FAILED: "Failed to load batch statistics.",
      LOAD_LOOKUPS_FAILED: "Failed to load batch management lookups.",
    },
  },

  /* -------- SYSTEM MANAGER DASHBOARD -------- */
  SYSTEM_MANAGER_DASHBOARD: {
    PAGE: {
      EYEBROW:   "Batch Supervisor Console",
      TITLE:     "System Manager Dashboard",
      SUBTITLE:  "Monitor your assigned batches and production pipeline",
      REFRESH:   "Refresh",
    },
    DATE_FILTER: {
      LABEL:      "Date Filter",
      TODAY:      "Today",
      THIS_WEEK:  "This Week",
      THIS_MONTH: "This Month",
      CUSTOM:     "Custom Range",
      START_DATE: "Start Date",
      END_DATE:   "End Date",
      VALUES:     { DAY: "day", WEEK: "week", MONTH: "month", CUSTOM: "custom" },
    },
    STATS: [
      { label: "Total Batches",  subLabel: "All assigned batches",  variant: "total" },
      { label: "In Progress",    subLabel: "Currently active",      variant: "inProgress" },
      { label: "Completed",      subLabel: "Fully processed",       variant: "completed" },
      { label: "Pending",        subLabel: "Awaiting approval",     variant: "pending" },
      { label: "Rejected",       subLabel: "Requires attention",    variant: "rejected" },
    ],
    ACTIVE_BATCHES: {
      SECTION_TITLE: "Active Batches",
      COLUMNS: ["Batch ID", "Motor ID", "Project", "Stage", "Sub-Stage", "Priority", "Status", "Progress", "Last Updated"],
      EMPTY:   "No active batches found.",
    },
    STAGE_STATUS: {
      TITLE:         "Stage Status",
      TOTAL_BATCHES: "Total Batches",
      COMPLETED:     "Completed",
      PENDING:       "Pending",
      EMPTY:         "No stage data for this period.",
      PERIOD: {
        day:    "Today",
        week:   "This Week",
        month:  "This Month",
        custom: "Custom Range",
      },
    },
    CHARTS: {
      MOTORS_PROCESSED: { TITLE: "Motors Processed", SUBTITLE: "Rocket motors processed & dispatched" },
      WEEKLY_ACTIVITY:  { TITLE: "Weekly Activity",  SUBTITLE: "Stage transitions this period" },
      STAGE_BREAKDOWN:  { TITLE: "Stage Distribution", SUBTITLE: "Batch count by processing stage" },
    },
    BATCH_STATUS: {
      SECTION_TITLE:     "Batch Status List",
      DETAILS_SECTION_TITLE: "Batch Status Details",
      SEARCH_PLACEHOLDER:"Search batches…",
      LAST_UPDATED_STAGE:"Last Completed Stage",
      CURRENT_STAGE:     "Current Stage",
      STAGE_HISTORY:     "Stage History",
      APPROVED_BY:       "Approved by",
      APPROVED_ON:       "On",
      MOTOR_ID:          "Motor ID",
      CREATED_ON:        "Created On",
      LAST_UPDATED_ON:   "Last Updated On",
      STAGE_TIMELINE:    "Stage Timeline",
      FIRST_STAGE_BADGE: "Stage 1 · Starting",
      NO_STAGE_DATA:     "No stage data available.",
      EMPTY:             "No batch status records found.",
    },
    ALERTS: {
      SECTION_TITLE: "Alerts & Bottlenecks",
      LIVE_BADGE:    "LIVE",
      FILTER_ALL:    "All",
      FILTER_ERROR:  "Errors",
      FILTER_WARNING:"Warnings",
      FILTER_INFO:   "Info",
      EMPTY:         "No alerts at this time.",
      BATCH_LABEL:   "Batch",
      STAGE_LABEL:   "Stage",
    },
    BLOCKCHAIN_EVENTS: {
      SECTION_TITLE:     "Block Traceability",
      IMMUTABLE_BADGE:   "IMMUTABLE",
      SEARCH_PLACEHOLDER:"Search transactions…",
      FILTER_LABEL:      "Filters",
      FILTER_EVENT_TYPE: "Event Type",
      FILTER_DEPT:       "Department",
      FILTER_SUBDEPT:    "Sub-Dept",
      FROM_LABEL:        "From",
      TO_LABEL:          "To",
      DATE_SEPARATOR:    "to",
      CLEAR_ALL:         "Clear all",
      EMPTY:             "No data available.",
      EVENT_TYPES: [
        "All", "STAGE_UPDATED", "APPROVAL_COMPLETED",
        "BATCH_CREATED", "BATCH_REJECTED", "DISPATCH_COMPLETED",
      ],
      DEPARTMENTS: [
        "All", "Sourcing", "Manufacturing", "Quality Control", "Dispatch",
      ],
    },
    FILTERS: {
      BUTTON:          "Filters",
      CLEAR_ALL:       "Clear all",
      SEARCH_BATCHES:  "Search batch ID, motor, project…",
      PRIORITY:        "Priority",
      STATUS:          "Status",
      DEPARTMENT:      "Department",
      PRIORITIES: ["All", "Low", "Medium", "High", "Critical"],
      STATUSES:   ["All", "in progress", "waiting for approval", "completed", "rejected"],
    },
    ERRORS: {
      LOAD_STATS_FAILED:  "Failed to load dashboard statistics.",
      LOAD_CHART_FAILED:  "Failed to load chart data.",
      LOAD_BATCHES_FAILED:"Failed to load active batches.",
      LOAD_ALERTS_FAILED: "Failed to load alerts.",
      LOAD_STATUS_FAILED: "Failed to load batch status list.",
      LOAD_EVENTS_FAILED: "Failed to load blockchain events.",
      LOAD_BATCH_DETAILS_FAILED: "Failed to load sub-department details.",
    },
    EMPTY_STATES: {
      NO_BATCHES: "No active batches match your filters.",
      NO_ALERTS:  "No alerts at this time. All systems operational.",
      NO_EVENTS:  "No blockchain events found.",
      NO_STATUS:  "No batch status records found.",
    },
  },
};
